### ISSUE TITLE
datastore: transaction succeeds, but client returns an error

### ISSUE THREAD

**Issue by karalabe** [GoogleCloudPlatform/gcloud-golang#100]
I've tried to execute a very simple transaction that just creates a database entry if the key doesn't exist yet.

However, even though my operations complete successfully, and the transaction itself is committed too (at least it appears in the datastore), the client API returns a `error during call, http status code: 400 The referenced transaction has expired or is no longer valid.` error.

Am I doing something terribly wrong, or is this an actual bug in the library?

```go
err := datastore.RunInTransaction(db.ctx, func(tc context.Context) error {
	log15.Debug("trying to obtain database lock")

	key := datastore.NewKey(tc, "TestEntity", "test_name", 0, nil)
	data := struct {
		Text string
	}{}
	if err := datastore.Get(tc, key, &data); err != nil && err != datastore.ErrNoSuchEntity {
		return err
	}

	data.Text = "Bla bla bla"
	if _, err := datastore.Put(tc, key, &data); err != nil {
		return err
	}
	return nil
})
fmt.Println("Transaction result:", err)
```

Output:
```
Transaction result: error during call, http status code: 400 The referenced transaction has expired or is no longer valid.
```

**Comment by karalabe** [comment]
Ok, it seems the error is in datastore.Put, which actually commits the transaction itself. Why would it do that?

**Comment by karalabe** [comment]
[Oh ffs, just deleted by comment instead of an undo].

So, in essence, the bug is that both `Put` as well as `RunInTransaction` commits before returning, resulting in a double commit and a completely meaningless result from `RunInTransaction`. I guess a simple solution would be to add some state variable into the context to verify if it was already committed and skip it in `RunInTransaction`.

I could do this fairly easily, though it would be a bit hackish. Maybe somebody has a better solution? In the mean time I can proceed working by escaping the last error out of the client function and discarding the result of `RunInTransaction`, but it's really really ugly.

**Comment by karalabe** [comment]
Fix proposal at https://code-review.googlesource.com/#/c/1721/ :)

**Comment by gmlewis** [comment]
From the comments in 1721, it appears that this was fixed in https://code-review.googlesource.com/#/c/1751
Closing.  Please re-open if this is not the case.
