### ISSUE TITLE
datastore: build is broken on Travis

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/gcloud-golang#103]
I'm not able to reproduce it locally, but the tests are failing on Travis.

https://travis-ci.org/GoogleCloudPlatform/gcloud-golang/jobs/46385498

**Comment by karalabe** [comment]
And the fix https://code-review.googlesource.com/#/c/1760/ ;)

Though I'm treading unfamiliar grounds, so you should definitely check it closely :)

**Comment by rakyll** [comment]
Obsolete, closing.
