### ISSUE TITLE
Can't run queries outside of the default namespace?

### ISSUE THREAD

**Issue by DallanQ** [GoogleCloudPlatform/gcloud-golang#104]
I'm trying to run a query outside the default namespace:

    testingCtx := datastore.WithNamespace(ctx, "test")
    key := datastore.NewKey(testingCtx, kind, "", id, nil)
    keys, err := NewQuery(kind).Ancestor(key).KeysOnly().GetAll(testingCtx, nil)

and getting an error:

    error during call, http status code: 400 The query namespace is &#39;null&#39; but ancestor namespace is &#39;test&#39;

It appears from this page https://cloud.google.com/datastore/docs/apis/v1beta2/datasets/runQuery that in order to run a query outside the default namespace, the request body has to explicitly include the namespace. But `query.go` doesn't set `RunQueryRequest.PartitionId.Namespace` from the passed-in context before calling `call(ctx, "runQuery", req, res)`. It seems like `query.go` should set the namespace in `req` before calling `call` in both the `Count` and `Run` functions, right?

**Comment by DallanQ** [comment]
Any update on this? Would it help if I submitted a pull request? It seems that on lines 401 and 540 of query.go, we need to add something along the lines of:

    req.PartitionId = &PartitionId{
        Namespace: ctxNamespace(ctx),
        DatasetId: // leave this nil?
    }

Would that be the correct fix?

**Comment by ItsLeeOwen** [comment]
+1  There definitely seems to be an issue with passing a namespaced context to GetAll.  The namespaced context is ignored, and if you have entities of the same kind in both a namespaced context, and default context, passing the namespaced context to GetAll will continue to return entities of the default context.

**Comment by adg** [comment]
I sent this fix: https://code-review.googlesource.com/2670

**Comment by adg** [comment]
@okdave Another person sent an equivalent fix (minus tests, which my change has). Not sure how this was missed; is nobody receiving notifications for incoming code reviews?

https://code-review.googlesource.com/#/c/2560/1

**Comment by okdave** [comment]
@adg Yikes. I don't know how to configure code-review to notify, but I'll look into it now.
