### ISSUE TITLE
compute/metadata: build is broken on GAE go1.4beta

### ISSUE THREAD

**Issue by karalabe** [GoogleCloudPlatform/gcloud-golang#105]
Please see:

 - https://groups.google.com/forum/#!topic/google-appengine-go/WeO8KGx6O8c
 - https://code-review.googlesource.com/#/c/1670/3 (my comment)

**Comment by rakyll** [comment]
Is this still an issue? https://code-review.googlesource.com/#/c/1780/ should have fixed it a while ago. Please re-open if necessary.
