### ISSUE TITLE
storage: add support for cache control

### ISSUE THREAD

**Issue by karalabe** [GoogleCloudPlatform/gcloud-golang#107]
Currently as far as I'm aware, the storage client does not support setting cache control fields, neither during creation, not by modifying object attributes. Since cache control cannot be set globally on a bucket, only individually on objects, this is an essential feature missing.

**Comment by rakyll** [comment]
Cache control is settable via the object attributes metadata field.

        w := storage.NewWriter(ctx, bucket, object)
        w.Metadata = map[string]string{
                "Cache-Control": "private, max-age=0, no-transform",
        }

**Comment by karalabe** [comment]
Ah, so that's where it's hidden. Thanks for the pointer.

**Comment by karalabe** [comment]
Doesn't work :P GCS sets the metadata into a nested set of headers, and doesn't use it directly as teh response header (essentially getting it ignored).

I.e. using the above code (slightly modified) returns an object with these headers (I'm playing with the expiration now):

```
Cache-Control:public, max-age=3600
x-goog-meta-Cache-Control:public, max-age=35
```

**Comment by karalabe** [comment]
Mailed https://code-review.googlesource.com/#/c/1900/

**Comment by rakyll** [comment]
Snap, I was able to use the metadata fields for the same purpose, seems to be broken now.

**Comment by ted-marozzi** [comment]
For anyone looking at this later its
```go
	w := obj.NewWriter(ctx)
	// One year as these should never change
	w.CacheControl = "private, max-age=31536000"
```

**Comment by Schachte** [comment]
Can you set cache-control to public on a private bucket?
