### ISSUE TITLE
storage: Names can be silently transformed when creating an object

### ISSUE THREAD

**Issue by jacobsa** [GoogleCloudPlatform/gcloud-golang#111]
`storage.NewWriter` accepts object names as Go `string`s, which are sequences of arbitrary bytes. It then (transitively) forwards them on to a JSON marshaller, which can represent only sequences of Unicode codepoints (cf. ECMA 404). The documentation for `json.Marshal` says this:

> String values encode as JSON strings coerced to valid UTF-8, replacing invalid bytes with the Unicode replacement rune.

The net result of this is that if I provide an object name like `b\xff` (a legal Go `string`) to `storage.NewWriter`, it causes my GCS bucket to contain an object with the unexpected name `b\xef\xbf\xbd` (represented in JSON as `b\ufffd`).

I think two things should be changed:

1. The documentation for the `storage` package should precisely specify what the space of legal object names is.

2. Requests to create an object with an illegal name should fail, and no object should be created.

It doesn't matter to me whether #2 is achieved by adding a check in the upstream generated `google.golang.org/api/storage/v1` package or in the wrapper (though the former is preferable), but as a user of the package it's what I should observe.

(This all probably applies to bucket names, too.)

**Comment by okdave** [comment]
Coming back to this after a long hiatus.

The storage docs now have [thorough descriptions for valid naming](https://cloud.google.com/storage/docs/bucket-naming). I'll add the highlights to this API and link out for the full reference.

@mcgreevy and I had a chat about the feasibility of doing this in the underlying generated APIs more generally. That looks like it will add a lot of complexity, unless we could get fuller support from the `encoding/json` package (the current coercing behaviour was added in Go 1.2). I think we'll leave the check local to object names unless we here about people running into this situation in other cases.

Fortunately bucket names are required to be a subset of ASCII, so this corruption won't affect the server's validity check.

**Comment by jacobsa** [comment]
Thanks, David!
