### ISSUE TITLE
storage: API should use structs or interfaces rather than free functions

### ISSUE THREAD

**Issue by jacobsa** [GoogleCloudPlatform/gcloud-golang#113]
The storage package is currently a grab bag of free functions:

 *  ACL
 *  BucketACL
 *  ListObjects
 *  (etc.)

(Side note: some of these are poorly named. I can't tell from its name what `ACL` does. It really should be called `GetObjectACLs` or similar.)

Because each of these is a free function, if I write code that operates on GCS I can't easily give it a fake GCS implementation for testing. Instead I, and every other user who cares, have to write my own wrapper struct/interface and then fake that. This is busy work for each of us, and it makes it impossible to offer an 'official' fake.

Additionally, the free function approach means that authorization material needs to be handed over anew on each call to the package. Currently this takes the form of a `context.Context` implementation with a magic entry in its value map that can only be checked at runtime. It is very easy to accidentally do the following:

```Go
type myRequestHandler struct {
  authenticatedTransportForGCS *http.Client
}

func (h *myRequestHandler) HandleRequest(ctx context.Context, ...) error {
  // Spot the bug!
  return storage.DeleteObject(ctx, "bucket", "object")
}
```

The bug is easy to miss at first glance. The handler is invoked with a context and must supply a context to `storage.DeleteObject`, so it's natural to just pass in `ctx`. And the compiler will be happy with that. But this will cause a run-time panic, because you should have remembered to instead call `cloud.NewContext`.

`myRequestHandler` shouldn't need to know about the authorization issues involved in the `storage` package; it should just be able to accept a struct representing a GCS bucket and call into it with its plain old request context (to support cancellation).

So for these reasons, I think the following would be a better approach:

1. The `storage` package defines interfaces like `Bucket`, containing methods like `NewWriter` and `DeleteObject`.

2. In order to get hold of a bucket, you call `storage.OpenBucket`, which accepts an `http.Client`. (Actually you probably do something like get a `Conn` object that lets you create, delete, and open buckets. But similar idea.)

3. Each method accepts a `context.Context`, so that it is cancellable. But the context is a plain old request context; it need not have any special junk added to its value map. So the `myRequestHandler` example above is not buggy.

4. Methods don't need to specify the bucket name; it is implicit in the bucket you are calling.

5. Optionally, the package provides good fakes for all of its interfaces, for use in tests.

Now code that calls GCS can be agnostic to how authorization works (it need only have a bucket interface injected). You can't screw up and forget to passthe right kind of context; instead the compiler checks that you've handed over  an HTTP transport at the right point. And in tests you can easily use fakes.

If it helps to see an example, [github.com/jacobsa/gcloud/gcs][gcs] is a partial implementation of this idea. There is a fake at [github.com/jacobsa/gcloud/gcs/gcsfake][gcsfake].

[gcs]: http://godoc.org/github.com/jacobsa/gcloud/gcs
[gcsfake]: http://godoc.org/github.com/jacobsa/gcloud/gcs/gcsfake

**Comment by rakyll** [comment]
> It really should be called GetObjectACLs or similar

In Go, you never prefix getters with Get. It could have been ObjectACL, but it's unnecessary verbose. Godoc explains what the call does well, it's quite obvious from the signature as well.

>  have to write my own wrapper struct/interface and then fake that.

No, you can provide your stub RoundTripper to the context to handle fake the responses. We should provide some testing utilities to make it easier/visible. The question is whether it's convenient to depend on network level mocking.

> Currently this takes the form of a context.Context implementation with a magic entry in its value map that can only be checked at runtime

Context objects are evil, but it was a sacrifice to keep the API surface similar to the Go AppEngine packages. I'm agreeing that a flat API surface with context.Context is not necessary and can be replaced by connection and service types. We can always box the type of the context, let's say, with cloud.Context, so you get the compilation-time errors.

**Comment by adg** [comment]
I don't think @jacobsa is suggesting removing the `context.Context` arguments from the calls; they're necessary in a lot of contexts. Just that providing the authentication via the context argument is wrong.

Take a look at the package he put together: http://godoc.org/github.com/jacobsa/gcloud/gcs

@jacobsa can you point me toward a usage of your API? I'm curious how it looks in practice, particularly the authentication stuff.

**Comment by okdave** [comment]
Also, I don't think a concrete type like `cloud.Context` would be a great solution here. Introducing our own context type would mean it wouldn't play well with standard context mechanisms, like timeouts.

I think if we took the "context"-ness out of `cloud.Context`, then we'd be left with something more akin to a Client. What @jacobsa is calling a `gcs.Conn`.

**Comment by rakyll** [comment]
> Just that providing the authentication via the context argument is wrong.

I do not think it's entirely wrong. If you authenticate with a service account, it's just awkward. Because the authentication is actually free from the request context. But from a user access token point of view, it makes sense to keep the auth bits in a value context. You may say putting an HTTP client in a value context is a bit extravagant, I'd agree with that.

> I think if we took the "context"-ness out of cloud.Context, then we'd be left with something more akin to a Client.

There is actually nothing contexty about the context we return from cloud.NewContext. And I wonder how contexty it can get. An HTTP connection is not abort-able, yet a timeout could be set. So, deadline and timeout issues should be decided at the initialization of the connection object (on the HTTP client). That's why I don't see a reason why we should keep having a context argument.

**Comment by dsymonds** [comment]
We should be aiming to get rid of `cloud.Context` and only use the standard `net.Context`. Anything that's special to an API should be attached to that as a context value, or passed as an explicit function argument, or be used to configure a Client type.

A context argument gives timeout/deadline control (on a per operation basis), and also tracing (e.g. dapper). An HTTP request is definitely abort-able (see the `CancelRequest` method). But if there's things that are outside the scope of a single request (e.g. auth details for a long-lived connection) then they don't belong in the context but rather in some other persistent value (e.g. a Client type).

**Comment by jacobsa** [comment]
@rakyll: You're right that you can fake RoundTripper, but that is extremely difficult compared to a fake for a service-specific interface -- it requires you to implement much more of the GCS stack than what the interface actually cares about (a map from keys to values).

I do think a plain old "golang.org/x/net/context"-type context should continue to be there, for essentially the reasons dsymonds said. But the HTTP client doesn't need to go in there for the usual reasons that layering is nice: the user of the interface doesn't care about the fact that the interface is implemented with an HTTP client, so they shouldn't have to hand it one. Just like I don't have to hand a file descriptor to an io.Reader that I was handed.

@adg: I have a real user of the package, but it's not yet open source. I've added you as a collaborator so you can see it. The Bucket interface is injected into the code in the fs/ directory, which therefore doesn't need to care about HTTP at all. See `getConn` in the root directory for the wiring code.

**Comment by jacobsa** [comment]
By the way, if it got lost in the noise: there is a fake that faithfully implements the Bucket interface [here](http://godoc.org/github.com/jacobsa/gcloud/gcs/gcsfake). Take a look at the source; it's quite easy to fake this sort of interface. It would be much more difficult to do it at the HTTP layer.

**Comment by rakyll** [comment]
A bit late, sorry.

@dsymonds, we wrap the generated client that doesn't expose the request objects. We need to provide a custom RoundTripper to capture the ongoing request and cancel it when time has come. I'm not sure how readable it will be, so some experimental work would be very valuable to evaluate this idea.

@jacobsa, we may think of providing some stub RoundTripper generators from a testutil package. I don't think introducing an interface and a concrete type is the approach in Go when it comes to testability. Browse the entire standard library and you won't see interface definitions for the sake of mockability.

I agree that we should keep the context argument and don't depend on the transport layer for any context-related functionality. Context may depend on the transport layer, but the transport layer shouldn't replace the context.

**Comment by jacobsa** [comment]
It doesn't have to be an interface type; a struct would be almost as good, because then the user can still define their own interface around it.

I disagree with your assessment of the standard library (assuming you mean to imply that a struct is also not a good choice). All over the place it uses structs and interfaces with methods in this sort of situation rather than free functions. The interface for writing to a file doesn't look like this:

```Go
func WriteToFile(fd int, p []byte) (int, error)
```

Instead you have an os.File struct, which you can inject into anything that expects an io.Writer or an io.WriteCloser, or even an os.File. The user doesn't have to manually carry around the file descriptor and hand it to free functions, which is something like manually carrying around an HTTP client.

**Comment by okdave** [comment]
This work was started in b467501b
