### ISSUE TITLE
Ack() should return more informative error messages

### ISSUE THREAD

**Issue by aaronkavlie-wf** [GoogleCloudPlatform/gcloud-golang#116]
I made a mistake in testing `pubsub.Ack()` and gave it a slice with a bunch of empty strings.
The error message returned for such mistakes is not informative; I didn't realize the mistake until I showed a Google engineer my code sample.

`log.Fatal(err)` gave me this:

`transport.go:90: googleapi: Error 500: Backend Error, backendError`

I would expect an error message telling me the input is invalid, and the reason why. Stuff like http status codes should probably not be included in error messages.

**Comment by tmatsuo** [comment]
How about to check if there are any empty strings before issuing the API call and returns an error?

**Comment by tmatsuo** [comment]
Just in case, I'm talking about adding that check within pubsub.Ack. If it sounds good, I'll create a CL.

**Comment by aaronkavlie-wf** [comment]
Sure, checking for empty strings in the library is sensible.

**Comment by tmatsuo** [comment]
On the second thought, I think this should be fixed on the server side. The server should return 400 status code ideally with a helpful error message.

WDYT?

**Comment by aaronkavlie-wf** [comment]
In my mind, both would be ideal.

You'd want the server to give you a sensible error for obvious errors like empty strings... but basic validation still seems sensible on the client as well, to avoid a round-trip to the server for obvious cases.

**Comment by tmatsuo** [comment]
Thanks, the CL sent:
https://code-review.googlesource.com/#/c/2290/1
