### ISSUE TITLE
NewReader and SignedURL naively construct incorrect and invalid URLs

### ISSUE THREAD

**Issue by jacobsa** [GoogleCloudPlatform/gcloud-golang#117]
In [multiple][1] [places][2] the storage package uses `fmt.Sprintf` to create URLs from arbitrary object names and hopes it will work out.

It doesn't work out. If you call `NewReader` with an object whose name is the string `"foo % bar"`, you get this error:

    parse https://storage.googleapis.com/jacobsa-gcs-integration-test/foo % bar: invalid URL escape "% b"

Similarly if the object is named `"foo \u0085 bar"`:

    storage: can't read object jacobsa-gcs-integration-test/foo  bar, status code: 400 Bad Request

I believe but have not confirmed that a clever name of the form `"foo?bar"` might cause the wrong object to be silently returned. This could be a security concern.

Each of these is a legal name according to the [documentation][names]. Obviously the package should support these without trouble. It should probably also have some tests for at least the most basic of troublesome names. :-/

[1]: https://github.com/GoogleCloudPlatform/gcloud-golang/blob/fffe461e194e54255fea3954c7197e300dc87811/storage/storage.go#L204
[2]: https://github.com/GoogleCloudPlatform/gcloud-golang/blob/fffe461e194e54255fea3954c7197e300dc87811/storage/storage.go#L265
[names]: https://cloud.google.com/storage/docs/bucket-naming#objectnames

**Comment by gmlewis** [comment]
Aaron, may I have permission to copy your test names into the cloud/storage library tests?
Taken from here: https://github.com/jacobsa/gcloud/blob/df00d97c20927fdeeb7f663172159a1d02f95ffd/gcs/gcstesting/bucket_tests.go

**Comment by gmlewis** [comment]
https://code-review.googlesource.com/#/c/2070/

**Comment by jacobsa** [comment]
Absolutely, please feel free to rip off anything you like. Note that the tests are for a different interface, though.

Regarding the code review: I'm not sure `url.QueryEscape` is correct to use here; the names don't go in the query after all. I think constructing a `url.URL` struct with the unescaped path in the `Path` member and then using `url.String()` might be better?

**Comment by gmlewis** [comment]
What if there is a slash in the name?  It seems like it is allowed by the documentation, but your approach would not distinguish between the slash separators and the slashes in the name(s), if I am reading the code correctly.  In fact, I think I need to add slashes to the test cases.  Do you agree?

**Comment by jacobsa** [comment]
The `InterestingNames` test [does](https://github.com/jacobsa/gcloud/blob/df00d97c20927fdeeb7f663172159a1d02f95ffd/gcs/gcstesting/bucket_tests.go#L345-L346) cover slashes. That said, I've not yet been able to make it pass because in addition to this bug in the Go package, there appears to be a related bug on the GCS end. Looking into it now.

In any case, I don't think a slash in the path is ambiguous, since bucket names can't contain a slash. The first component of the path is the bucket, then there's a slash, then everything else (including slashes) is the object name.

**Comment by gmlewis** [comment]
Aaron - you are right.  I commented in the code review.  Thanks.

**Comment by rakyll** [comment]
What's the status of this issue? I am blocked by the same case.

**Comment by jacobsa** [comment]
I stopped using this package so I'm not sure of the status here, but I wrote my own decently-tested code with no known bugs that you can feel free to take from. [Here](https://github.com/jacobsa/gcloud/blob/bd772366fca7149515be3ad39a0f2a60bdf360b0/gcs/read.go#L34-L63) is the code that constructs a URL for reading an object, and [this](https://github.com/jacobsa/gcloud/blob/bd772366fca7149515be3ad39a0f2a60bdf360b0/httputil/path.go) is the code that it calls for constructing path segments according to the RFC.

**Comment by gmlewis** [comment]
https://code-review.googlesource.com/#/c/2070/
I'm confused by the current state of the review, and I don't know if any action is needed on my part.
I believe that this is a correct solution and the unit tests pass.
@okdave - can this be rebased and submitted?

**Comment by gmlewis** [comment]
Thanks, Dave!
Fixed.  Closing.

**Comment by gmlewis** [comment]
@JustinBeckwith - why would the Yoshi bot assign "triage me" labels to closed issues?
(And why are you assigning closed issues to me that are many years old? :joy: )
