### ISSUE TITLE
Logging API ?

### ISSUE THREAD

**Issue by PSG-Luna** [GoogleCloudPlatform/gcloud-golang#119]
Is a logging API using the new cloud logging functionality currently in alpha something that'd be interesting for this package ? It seems to fit in well with the rest

I'd be willing to contribute an API for this, similar to the one of the default log package in Go

**Comment by gpopovic** [comment]
Looking forward to the logging api

**Comment by rakyll** [comment]
@bradfitz showed some interested to work on it. I am not sure about his progress.

**Comment by bradfitz** [comment]
I have a working package. I haven't mailed it yet. I keep getting distracted with unrelated broken things.

**Comment by gpopovic** [comment]
@bradfitz any news about it?

**Comment by christopherhesse** [comment]
@bradfitz Any chance you could post the pre-release version somewhere so I can base my work off of the future gcloud logging package rather than writing my own?

**Comment by rakyll** [comment]
There is a CL, about to be finalized at https://code-review.googlesource.com/#/c/2650/.

**Comment by christopherhesse** [comment]
Awesome, thanks!

**Comment by bradfitz** [comment]
It is now submitted:
https://godoc.org/google.golang.org/cloud/logging

**Comment by bradfitz** [comment]
I lack permissions to close this bug.
