### ISSUE TITLE
Go SDK example missing 

### ISSUE THREAD

**Issue by Karthic-Hackintosh** [GoogleCloudPlatform/gcloud-golang#121]
https://cloud.google.com/appengine/articles/logging contains the example for Python , Java SDk , this would be a discouraging sign for a Go Runtime User . It would be great if a third tag containing GO SDK is added along the existing code samples

**Comment by gmlewis** [comment]
Logging in Go is very simple:
https://cloud.google.com/appengine/docs/go/requests#Go_Logging

**Comment by Karthic-Hackintosh** [comment]
In the Go Runtime  i used the method c.Infof to log messages , but it fails to compile with the following error 
***c.Infof undefined (type context.Context has no field or method Infof)*** .
The Error clearly tells that the app engine context returned from ***c := appengine.NewContext(r)*** is of type ***context.Context*** and it doesnt have a method ***c.Infof*** on it. But contrary to this the documentation in https://godoc.org/google.golang.org/appengine/log suggests that this method exists . Another point to note , The method existed on the context returned by "appengine" (import "appengine" ) package , and this doesnt seem to exist on the context returned by the new package ***google.golang.org/appengine*** (It broke only after moving from "appengine" to "google.golang.org/appengine") , what is ***c.Infof*** equivalent on the new Context of type context.Context returned by package ***"google.golang.org/appengine"*** ?

**Comment by PSG-Luna** [comment]
You should import "google.golang.org/appengine/log" and do log.Infof(c, ...)

**Comment by gmlewis** [comment]
Ah, yes.  You need to read the very first message from Dave Symonds here:
https://groups.google.com/forum/#!topic/google-appengine-go/RAFdSTwo34w

If it used to look like this with the "appengine" import:
```go
import "appengine"
...
c.Criticalf("msg")
c.Debugf("msg")
c.Errorf("msg")
c.Infof("msg")
c.Warningf("msg")
```
then it will now look like this with the "google.golang.org/appengine/log" import:
```go
import "google.golang.org/appengine/log"
...
log.Criticalf(c, "msg")
log.Debugf(c, "msg")
log.Errorf(c, "msg")
log.Infof(c, "msg")
log.Warningf(c, "msg")
```

These functions are documented in the link that you gave: https://godoc.org/google.golang.org/appengine/log

**Comment by Karthic-Hackintosh** [comment]
Gotcha ! Thank You :)

**Comment by Karthic-Hackintosh** [comment]
But the Documentation at https://godoc.org/google.golang.org/appengine/ should have stated to use log.Infof(c,"info") !!
