### ISSUE TITLE
 ModifyAckDeadline does not convert deadline to seconds

### ISSUE THREAD

**Issue by swalkowski** [GoogleCloudPlatform/gcloud-golang#124]
It looks like there is a missing division by time.Second in this line:

https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/pubsub/pubsub.go#L116

which makes the whole function work incorrect.

**Comment by rakyll** [comment]
Mailed https://code-review.googlesource.com/#/c/2600/.

**Comment by gmlewis** [comment]
Fixed by @rakyll in https://github.com/GoogleCloudPlatform/gcloud-golang/commit/b0ed34171eb0f730dda336155af9a3f60aa203b0
Closing.
