### ISSUE TITLE
storage: integration test bucket name variable not used

### ISSUE THREAD

**Issue by solidsystem** [GoogleCloudPlatform/gcloud-golang#125]
When running the integration test for the storage library locally, the documentation says to set environment variable GCLOUD_TESTS_GOLANG_BUCKET_NAME to determine what bucket to run test in (https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/CONTRIBUTING.md#integration-tests).

In the source code I find that GCLOUD_TESTS_GOLANG_PROJECT_ID was used instead. I've created a patch to fix this in the testcode:

https://code-review.googlesource.com/#/c/2160/

I think I later saw a comment somewhere that the current behaviour was desired. If that's the case I guess the documentation should be updated instead.

PS: I also wonder; Should I always create issues like this before of after sending patches to gerrit? I uploaded my patch march 30th, and haven't received any feedback, so I guess no one looks at incoming patches there? Some clarification to this in the CONTRIBUTING.md file would be helpful.

**Comment by gmlewis** [comment]
Yes, I came across this too and made the same PR, but it was rejected as "Working as intended."

Please feel free to create a PR to fix the documentation for the integration test.

I'll leave this issue open to track that progress, and so that others don't do the same thing.

**Comment by rakyll** [comment]
The rest of the other package tests require a `GCLOUD_TESTS_GOLANG_PROJECT_ID` env variable. My intention was to reuse it and avoid user to set an additional env variable.

A better alternative is to create a bucket programmatically before the tests begin and delete it afterwards.

**Comment by solidsystem** [comment]
I created a PR to fix the documentation:

https://code-review.googlesource.com/#/c/2630/

**Comment by rakyll** [comment]
Thanks! 629ed086d82ad5d0ac3668e309b8785aaf54735b closed the issue.
