### ISSUE TITLE
make bigquery use new ClientOption

### ISSUE THREAD

**Issue by okdave** [GoogleCloudPlatform/gcloud-golang#128]
As per bigtable, bigquery should follow the `pubsub.NewClient(foo, ...cloud.ClientOption)` pattern

See bcd419df

**Comment by nightlyone** [comment]
@mcgreevy / @okdave do you want a little help with this?

I would like to use this library with appengine and need support for https://godoc.org/google.golang.org/cloud#WithBaseHTTP so this works.

**Comment by mcgreevy** [comment]
Sure, feel free to send me a patch.
