### ISSUE TITLE
storage: clarify if calls can be used on "folders"

### ISSUE THREAD

**Issue by eaigner** [GoogleCloudPlatform/gcloud-golang#132]
The docs should make clear if `storage.DeleteObject` (and similar calls) can operate on objects ("folders") with children ("subdirectories").

PS: Is it possible?

**Comment by gmlewis** [comment]
Google Cloud Storage does not have separate objects of type "folder".
Instead, if objects have slashes in the name, they can be grouped and browsed in virtual "folders" from the GCS browser, but as soon as the last object is deleted from a virtual "folder", that "folder" no longer exists.
Check out https://cloud.google.com/storage/docs/overview for more information.

**Comment by eaigner** [comment]
I was just pointing out that the documentation of methods like `storage.DeleteObject` doesn't make it clear that this would only work on a single object, and not on a prefix (like with a `Query`).

I was actually expecting that when I have 2 objects

- `path/to/obj/a.txt`
- `path/to/obj/b.txt`

and I call `DeleteObject(ctx, bucket, "path/to/obj")`, both would be deleted.

**Comment by gmlewis** [comment]
Oh, I see.  Thanks, Erik.
@okdave - What if we were to provide a `storage.DeleteFolder` method that would first query all objects in the virtual folder and then delete them all?
In the same PR, we could improve the documentation of `storage.DeleteObject`.

**Comment by eaigner** [comment]
That would be great, although I think `DeletePrefix` would be more appropriate to match the GCS terminology.

**Comment by okdave** [comment]
I would err on just improving the documentation for `DeleteObject` now. `DeletePrefix` actually sounds like it would be better implemented as an example or helper utility: I don't think this library can implement it any more efficiently internally than could be done using the external API, and it would be a good way to demonstrate how the code should be invoked.

**Comment by adg** [comment]
I don't think it's feasible for us to provide a wildcard-matching delete.
What about buckets with hundreds of thousands or millions of objects?

**Comment by eaigner** [comment]
@adg I don't see it that way. It's true that a user could misuse a `DeletePrefix` methods, but no more than doing it via the snippet provided in the docs.

```
// List all files with the given page prefix.
query := &storage.Query{
	Prefix: prefix,
}
for {
	objects, err := storage.ListObjects(ctx, bucket, query)
	if err != nil {
		return err
	}
	for _, obj := range objects.Results {
		err = runOperationOnObj(obj)
		if err != nil {
			return err
		}
	}
	// If there are more results, objects.Next will be non-nil.
	query = objects.Next
	if query == nil {
		break
	}
}
return nil
```

At least a `DeletePrefix(prefix string, maxItems int)` would actively remind the user that this could be an expensive operation by having to specify the `maxItems` parameter (or `-1` for all).

**Comment by okdave** [comment]
@eaigner is there anything about `DeletePrefix` that could not be built on top of the existing API, or that is terribly subtle?

**Comment by eaigner** [comment]
No not really. It was just a suggestion.

**Comment by adg** [comment]
IMO it's better for the API to confront the user with the cost (many list
and delete calls), and allow them to handle the spefici failures of each.
If we provide a single wildcard-matching delete method then we need to
provide a complex error reporting structure to indicate partial failures.
Doesn't seem worth it, on balance.
