### ISSUE TITLE
bigtable: support conjunctive filters for CondMutation

### ISSUE THREAD

**Issue by hjfreyer** [GoogleCloudPlatform/gcloud-golang#137]
AFAICT, there's no way given the current API to apply a mutation if any only if a row contains, say, column A AND column B.

The proto lists support for a RowFilter_Condition, but a) that's not wrapped in the API, and b) the comment seems to suggest than an implementation of A && B wouldn't be checked atomically, which makes it often unsuitable.

With SkipFilter, one could implement "A && B" as "Skip(1, Interleave(A, B))" (assuming A and B produce as most one value), but Skip isn't supported according to https://cloud.google.com/bigtable/docs/hbase-differences

Or is there another way that I'm missing?

**Comment by hjfreyer** [comment]
Aha, it seems that there's support for skipping items in bigtable_data.proto, by way of CellsPerRowOffsetFilter.

Maybe the library should have a ProtoFilter which lets your build the proto manually if you Know What You're Doing :tm:?

**Comment by dsymonds** [comment]
We're unlikely to ever support exposing the proto API directly.

We can certainly implement missing filters, though. I'm not sure `cells_per_row_offset_filter` satisfies your original use case. Can you describe how that would work?

**Comment by dsymonds** [comment]
Please open new issues for any specific filters in the proto that you'd like supported.
