### ISSUE TITLE
code reviewing tool instructions are incorrect

### ISSUE THREAD

**Issue by smreed** [GoogleCloudPlatform/gcloud-golang#139]
Current version of CONTRIBUTING.md has instructions to run `go get golang.org/x/review/git-review`, which produces an error and the following output:

```
package golang.org/x/review/git-review
	imports golang.org/x/review/git-review
	imports golang.org/x/review/git-review: cannot find package "golang.org/x/review/git-review" in any of:
	/usr/local/go/src/golang.org/x/review/git-review (from $GOROOT)
	/home/smreed/go/src/golang.org/x/review/git-review (from $GOPATH)
```

However `go get golang.org/x/review/git-codereview` seems to work.

**Comment by gmlewis** [comment]
https://code-review.googlesource.com/#/c/2920

**Comment by nileshjagnik** [comment]
This command seems to work. Not sure if this is the correct tool
`go get golang.org/x/review/git-codereview`
