### ISSUE TITLE
bigtable: decodeFamilyProto uses sprintf when simple concatenation is faster

### ISSUE THREAD

**Issue by smreed** [GoogleCloudPlatform/gcloud-golang#140]
https://code-review.googlesource.com/#/c/2930

For small strings it is faster to use naive concatenation instead of `fmt.Sprintf`. I'm happy to post a benchmark if necessary.

**Comment by dsymonds** [comment]
While that's true, it loses a little bit of clarity in the formatting, and the speed difference is insignificant once you're actually making RPCs. I'd prefer to leave it as is for now.
