### ISSUE TITLE
Google Storage: googleapi: Error 404: Not Found, notFound

### ISSUE THREAD

**Issue by kit1989** [GoogleCloudPlatform/gcloud-golang#141]
I am trying to use Google Storage to upload a file. I have successfully uploaded a file with the same code base in dev environment which use service json for authorization. However, when I deploy same code in GCE and try to upload a file, the server return "googleapi: Error 404: Not Found, notFound" to me. I have checked the permission of my instance. It is full-control for Google Storage. What's the problem? 

The following is my authorization method to return "context"

```
func GetAuth() (ctx *context.Context) {
	var _ctx context.Context

	if IsDev() {
		jsonKey, err := ioutil.ReadFile("path-to-my-json")
		if err != nil {
			log.Panic(err)
		}

		conf, err := google.JWTConfigFromJSON(
			jsonKey,
			datastore.ScopeDatastore,
			datastore.ScopeUserEmail,
			storage.ScopeFullControl,
		)
		if err != nil {
			log.Panic(err)
		}

		_ctx = cloud.NewContext("my-project", conf.Client(oauth2.NoContext))
	} else {
		client := &http.Client{
			Transport: &oauth2.Transport{
				// Fetch from Google Compute Engine's metadata server to retrieve
				// an access token for the provided account.
				// If no account is specified, "default" is used.
				Source: google.ComputeTokenSource(""),
			},
		}

		_ctx = cloud.NewContext("my-project", client)
	}

	ctx = &_ctx

	return
}
```

This is my "default" scope retrieving from GCE

```
https://www.googleapis.com/auth/bigquery
https://www.googleapis.com/auth/cloud-platform
https://www.googleapis.com/auth/compute
https://www.googleapis.com/auth/datastore
https://www.googleapis.com/auth/devstorage.full_control
https://www.googleapis.com/auth/logging.admin
https://www.googleapis.com/auth/monitoring
https://www.googleapis.com/auth/sqlservice.admin
https://www.googleapis.com/auth/taskqueue
https://www.googleapis.com/auth/userinfo.email
```

**Comment by gmlewis** [comment]
Which call is returning this error?  It sounds to me like your Objects.Insert call is missing the object's name.  If it were me, I would debug this by instrumenting the call to get the full response from the server when the Objects.Insert call is being made.

**Comment by kit1989** [comment]
Finally, I found the issue. It's my fail. I am using different config in GCE environment and I haven't create any bucket for that environment. Thanks for you reply @gmlewis
