### ISSUE TITLE
Unable to upload files bigger than 10mb through app engine

### ISSUE THREAD

**Issue by Eksrow** [GoogleCloudPlatform/gcloud-golang#144]
``` 
import (
   "golang.org/x/net/context"
    "golang.org/x/oauth2/google"
    "golang.org/x/oauth2"
    "google.golang.org/cloud/storage"
    "google.golang.org/cloud"

    newappengine "google.golang.org/appengine"
    newurlfetch "google.golang.org/appengine/urlfetch"
)

  func GetGCloudContext(cn context.Context) context.Context{
    return cloud.NewContext(newappengine.AppID(cn), &http.Client{
        Transport: &oauth2.Transport{
            Source: google.AppEngineTokenSource(cn, storage.ScopeFullControl),
            Base:   &newurlfetch.Transport{Context: cn},
        },
    })
}

func StoreUpload(cn context.Context, header *multipart.FileHeader, mediaFile io.Reader, filename string) (string, error) {
    writer := storage.NewWriter(GetGCloudContext(cn), models.EXTERNAL_BUCKET, "upload/" + filename)
    writer.ContentType = header.Header["Content-Type"][0]

    bytesWritten, err = io.Copy(writer, mediaFile)

    if err != nil {
        return "", err
    }

    cn.Debugf("Bytes written: %+v", bytesWritten) //This will accurately report the amount of bytes written even if it exceeds 10mb.

    writer.Close()
}
```

For some reason this code works perfectly fine for files smaller than 10mb, but once it exceeds the files no longer appear on the app engine bucket browser. I've tried different writers like bufio and ioutil's readAll, they all report the same number of bytes written but files bigger than 10mb aren't available on GCS.

This started happening when I changed from the File api to the new cloud/storage package.
This problem also appeared before the update when you could still pass appengine.Context to oauth2.Transport, it was then that I realized I was using older libraries. I'm 100% certain I have up to date libraries now.

I'm not sure what else I can provide for information.

--Edit--

Directly POSTing to the cloud endpoint does work correctly.
The problem also persists on a new bucket.

**Comment by ianrose14** [comment]
I believe this is because urlfetch (which you have to use on appengine to POST to GCS) is limited to a 10MB request payload.  https://cloud.google.com/appengine/docs/python/urlfetch/#Python_Quotas_and_limits

**Comment by Eksrow** [comment]
I can't believe I wasted an entire day on this....

Thanks for the help ian.
