### ISSUE TITLE
storage: PutBucketACLRule currently broken by GCS Storage API

### ISSUE THREAD

**Issue by gmlewis** [GoogleCloudPlatform/gcloud-golang#147]
Leaving this issue open until we get a resolution from the GCS Storage team.

**Comment by stephenplusplus** [comment]
Just a heads up we received an update over here: https://github.com/GoogleCloudPlatform/gcloud-node/issues/716#issuecomment-125346513

**Comment by gmlewis** [comment]
https://code-review.googlesource.com/#/c/3370

**Comment by gmlewis** [comment]
The Google Cloud Storage team has fixed the issue on the backend.
Re-instituting test.
