### ISSUE TITLE
bigtable: update bttest docs

### ISSUE THREAD

**Issue by derekperkins** [GoogleCloudPlatform/gcloud-golang#151]
Normally I'd just open a PR for this, but there's a little too much overhead for now.
```
srv, err := bttest.NewServer()
client, err := bigtable.NewClient(ctx, proj, zone, cluster,
	bigtable.WithCredentials(nil), bigtable.WithInsecureAddr(srv.Addr))
```
should be changed to:
```
srv, err := bttest.NewServer()
conn, err := grpc.Dial(srv.Addr)
client, err := bigtable.NewClient(ctx, proj, zone, cluster, cloud.WithBaseGRPC(conn))
```

**Comment by tartavull** [comment]
in the commit you made you wrote:
```
bigtable.WithBaseGRPC(conn))
```
Should'nt this be? :
```
cloud.WithBaseGRPC(conn))
```

**Comment by dsymonds** [comment]
You're right. Thanks. I'll fix that.

**Comment by tartavull** [comment]
Allthough I follow this code and I get:

Error applying ReadModifyWrite to row
rpc error: code = 2 desc = "grpc: the client connection is closing"

Any ideas of what might I be doing wrong?

**Comment by dsymonds** [comment]
Sorry, that's a different error entirely. Check you've got an up-to-date grpc and any other dependencies.

**Comment by tartavull** [comment]
Thanks, I've just figure it out.
I was adapting the hello-world bigTable example to use bttest. And when the bigTable Admin  Client is close, it shutdowns the connection. So you have to create a new connection for the new bigTable Client.
I wasn't obvious for me that I had to do this from the documentation.
