### ISSUE TITLE
Error in "go get google.golang.org/cloud/datastore"

### ISSUE THREAD

**Issue by browny** [GoogleCloudPlatform/gcloud-golang#153]
Below are errors when execute `go get google.golang.org/cloud/datastore`

/Go/ext/src/google.golang.org/cloud/datastore/datastore.go:215: undefined: MultiError
/Go/ext/src/google.golang.org/cloud/datastore/datastore.go:236: undefined: typeOfPropertyList
/Go/ext/src/google.golang.org/cloud/datastore/datastore.go:240: undefined: typeOfPropertyLoadSaver
/Go/ext/src/google.golang.org/cloud/datastore/datastore.go:271: undefined: MultiError
/Go/ext/src/google.golang.org/cloud/datastore/datastore.go:307: undefined: MultiError
/Go/ext/src/google.golang.org/cloud/datastore/datastore.go:344: undefined: loadEntity
/Go/ext/src/google.golang.org/cloud/datastore/datastore.go:368: undefined: MultiError
/Go/ext/src/google.golang.org/cloud/datastore/datastore.go:443: undefined: saveEntity
/Go/ext/src/google.golang.org/cloud/datastore/datastore.go:463: undefined: MultiError
/Go/ext/src/google.golang.org/cloud/datastore/query.go:346: undefined: interfaceToProto
/Go/ext/src/google.golang.org/cloud/datastore/query.go:346: too many errors

**Comment by broady** [comment]
Probably a problem on your end. This works fine for me, could you try it?
`$ GOPATH=$TMPDIR go get google.golang.org/cloud/datastore`

**Comment by browny** [comment]
yes, go get now works, but some strange issue happens

When I import "google.golang.org/cloud/datastore" in my code, several function shown as `undefined` when I run `go build` (as below error)

But, if I reset to several commit before in `google.golang.org/cloud/datastore` in GOPATH, above issue was gone

    rtc-middle/gds/gdsmanager.go:52: undefined: "google.golang.org/cloud/datastore".Put
    rtc-middle/gds/gdsmanager.go:94: undefined: "google.golang.org/cloud/datastore".Get
    rtc-middle/gds/gdsmanager.go:112: undefined: "google.golang.org/cloud/datastore".GetMulti
    rtc-middle/gds/gdsmanager.go:143: undefined: "google.golang.org/cloud/datastore".Delete
    rtc-middle/gds/gdsmanager.go:157: query.GetAll undefined (type *"google.golang.org/cloud/datastore".Query has no field or method GetAll)
    rtc-middle/gds/gdsmanager.go:180: query.Count undefined (type *"google.golang.org/cloud/datastore".Query has no field or method Count)
    rtc-middle/gds/gdsmanager.go:216: undefined: "google.golang.org/cloud/datastore".NewTransaction 

My env is as below:

GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.4.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.4.2/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

**Comment by browny** [comment]
I found it seem due to this a backwards incompatible change, I will change my code first, thanks

https://github.com/GoogleCloudPlatform/gcloud-golang/commit/14ff860d19a87fb91816f2cb19c73e059a09e0e4

**Comment by broady** [comment]
Yup, that's it!
