### ISSUE TITLE
compute/metadata imports another library's internal code and doesn't compile with 1.5

### ISSUE THREAD

**Issue by krousey** [GoogleCloudPlatform/gcloud-golang#160]
```console
> go version
go version go1.5 linux/amd64
> go build
package github.com/GoogleCloudPlatform/gcloud-golang/compute/metadata
	imports google.golang.org/cloud/internal: use of internal package not allowed
```

**Comment by gmlewis** [comment]
I'm unable to reproduce the error with a simple test case I wrote.
Did you `go get google.golang.org/cloud/compute/metadata`?
It looks like you may have retrieved the package using `git clone` instead of `go get`.
Can you try that, please?

**Comment by krousey** [comment]
A dependency we had in Kubernetes imported through the github url instead of google.golang.org. It's been fixed here: https://github.com/google/cadvisor/pull/859
