### ISSUE TITLE
[bigtable] need more filter support in bttest

### ISSUE THREAD

**Issue by hsinhoyeh** [GoogleCloudPlatform/gcloud-golang#161]
we would like to use bttest to test our library which uses bigtable's client to read/write data.
in our case, we use the following filter:
ColumnFilter(xxx), LatestNFilter(xxx), InterleaveFilters() and ChainFilters()

however the current implementation (
https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/bigtable/bttest/inmem.go#L268
) has implemented limited filters which is barely satisfy our requirement.
Do you have a road map to support that? Or you can accept a PR?

**Comment by dsymonds** [comment]
bttest should already support ColumnFilter and LatestNFilter. The only two missing from your list are InterleaveFilters and ChainFilters. That should be easy enough for me to do.

(In general, just file an issue for any filters you want implemented; I'll add them on demand.)

**Comment by dsymonds** [comment]
Correction: ChainFilters should already work with bttest. It is only InterleaveFilters that is missing.

**Comment by hsinhoyeh** [comment]
thanks
