### ISSUE TITLE
datastore: error during call, http status code: 412 no matching index found.

### ISSUE THREAD

**Issue by kit1989** [GoogleCloudPlatform/gcloud-golang#163]
Hi 

When I try to do a query on Google Datastore, I got the following error message from Google Datastore. 

*error during call, http status code: 412 no matching index found.*

I read the docuementation in Google Cloud : https://cloud.google.com/appengine/docs/go/datastore/queries#Go_Restrictions_on_queries

It shows an example mix with equality (=) and inequality filter in a query. So, I do the following the query.

```javascript
return datastore.NewQuery(table).
		Filter("status=", "active").
		Filter("geohashes >=", swHash).
		Filter("geohashes <=", neHash).
		Limit(limit)
```

However,  it returns the following message:

*error during call, http status code: 412 no matching index found.*

I have try these two combinations: 
#### Only status

```javascript
return datastore.NewQuery(table).
		Filter("status=", model.StatusActive).
		Limit(limit)
```

#### Only inequality 
```javascript
return datastore.NewQuery(table).
		Filter("geohashes >=", swHash).
		Filter("geohashes <=", neHash).
		Limit(limit)
```

Both works. But cannot mix together. I am 100% sure that I have added index for both property.
Is my query valid?

**Comment by okdave** [comment]
@kit1989 it looks like your query is valid, but you need to define additional indexes before it will work.

If you read the [docs about datastore index](https://cloud.google.com/datastore/docs/concepts/indexes) you will see that there are automatically indexes for many cases. However you need to manually define an index for "Queries with one or more inequality filters on a property and one or more equality filters on other properties".

You will need to use the `gcd` tool to define your additional indexes. See the page above for more info on that. (In the app engine environment, the development server will automatically discover which indexes need to be generated – but it doesn't sound like that's the environment you're using here).
