### ISSUE TITLE
[bigtable] need lastNFilter support in bttest

### ISSUE THREAD

**Issue by hsinhoyeh** [GoogleCloudPlatform/gcloud-golang#165]
this issue is related to  #161, where we need more filter support in bttest.
we use the latest code and found that LastNFilter is still missing.
would you like to check that? the logs we got
```
2015/09/03 22:28:30.243836 inmem.go:281: WARNING: don't know how to handle filter (ignoring it): &{1}
2015/09/03 22:28:30.243862 inmem.go:282: WARNING: *google_bigtable_v1.RowFilter_CellsPerColumnLimitFilter
```
and that is what lastNFilter used 
https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/bigtable/filter.go#L142

**Comment by dsymonds** [comment]
How are you composing your filters? I guess you're using LatestNFilter inside another filter?

**Comment by hsinhoyeh** [comment]
yap, more like this
```
bgt.ChainFilters(bgt.InterleaveFilters(xxx), bgt.LatestNFilter(xxx))
```
