### ISSUE TITLE
metadata client broken in Go 1.5

### ISSUE THREAD

**Issue by evandbrown** [GoogleCloudPlatform/gcloud-golang#167]
The [client for retrieving GCE metadata](https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/compute/metadata/metadata.go#L50) imports `google.golang.org/cloud/internal` to [create a transport](https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/compute/metadata/metadata.go#L50) for the metadata client. The new imports convention in Go 1.5 isn't cool with that. Should `internal.Transport` be externalized, or its functionality ("Transport is an http.RoundTripper that appends Google Cloud client's user-agent to the original request's user-agent header.") replicated in current clients? In the metadata case, I believe that just means adding the `Metadata-Flavor: Google` header.

**Comment by adg** [comment]
Broken you say? Are you importing it as `"google.golang.org/cloud/compute/metadata"`? Because that shouldn't run afoul with the internal package rules.

**Comment by evandbrown** [comment]
It's not obvious to a new user of this package (and others that mirror google.golang.org) that the import provenance matters. GitHub is the first search result I got for 'golang gce metadata', and importing from there worked for months before switching to 1.5. So yeah, broken.

Brad fixed it this morning; https://code-review.googlesource.com/#/c/3372/2/compute/metadata/metadata.go
