### ISSUE TITLE
Most of the Examples in the Docs  are still pointing to appengine/* package 

### ISSUE THREAD

**Issue by Karthic-Hackintosh** [GoogleCloudPlatform/gcloud-golang#168]
Most of the examples in the Docs , like the one in this link https://cloud.google.com/appengine/docs/go/memcache/ , still pointing to `appengine/*` package , even these have been moved to `"google.golang.org/appengine/*` . This is really misleading for those who are new to the platform . Can there be a update in the docs ?

**Comment by broady** [comment]
Assigning to myself to make sure I follow up.

If someone else wants to work on this, feel free to re-assign.

**Comment by okdave** [comment]
This is fixed. @broady please reopen if anything was still outstanding.
