### ISSUE TITLE
CI failed in master branch

### ISSUE THREAD

**Issue by laco0416** [GoogleCloudPlatform/gcloud-golang#173]
CI status is error.

https://travis-ci.org/GoogleCloudPlatform/gcloud-golang

Please keep `master` branch ALWAYS green.

**Comment by vvakame** [comment]
Our product can't build now...
We use appengine/go.
appengine/go is go 1.4, not go 1.5.
1.4 not supported vendor directory...

**Comment by broady** [comment]
dupe of #171
