### ISSUE TITLE
[bigtable] simulate GC policy in bttest

### ISSUE THREAD

**Issue by hsinhoyeh** [GoogleCloudPlatform/gcloud-golang#176]
@dsymonds per code review comments, you mentioned that you will think a good way to simulate GC policy.
this issue is used to track that status. have it closed if you think it is done.

**Comment by dsymonds** [comment]
Yep, I've been thinking about it. I'll take care of this.

**Comment by hsinhoyeh** [comment]
thanks for fixing that.
I think there is a case that the current impl cannot handle: caller calls Read but GC is not triggered yet.
We still need to apply gc policy in the Read operations, or we need to apply filter (like lastNFilter) in client side.
how do you think about that?
btw, do you have documentations on how bigtable handle gc policy? thanks

**Comment by dsymonds** [comment]
This is an accurate simulation in that regard. In production, GC policy is _not_ applied on reads, so if you require that then you need to handle that manually. GC will only happen periodically (maybe hours or days afterwards). This is mentioned in the `SetGCPolicy` docs (https://godoc.org/google.golang.org/cloud/bigtable#AdminClient.SetGCPolicy), though perhaps not as explicitly as it could be.

**Comment by hsinhoyeh** [comment]
maybe we can update docs in detail.

Right now we use SetGCPolicy in server side and apply LatestNFilter in client side. It works.
thanks
