### ISSUE TITLE
bigtable/bttest: make data stateful

### ISSUE THREAD

**Issue by hsinhoyeh** [GoogleCloudPlatform/gcloud-golang#177]
Hi,
[this is feature proposal on bttest]

bttest implements table in memory,
https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/bigtable/bttest/inmem.go#L653
which works pretty well and fast.
Storing things in modern machines are not a problem, but we will lose them once we restart bttest server.

If we keep data in disk, here are pros and cons that I can merely think of:
Pros:
the data is more stateful. we won't lost any things unless the dumped file is corrupted.
Cons:
it could take time to dump table into disk, but mmap could be helpful.

how do you think about that?

**Comment by dsymonds** [comment]
I don't think that's a direction that bttest is going to take. It's always been an in-memory fake simulation. It isn't intended for actual use, only for testing.
