### ISSUE TITLE
storage: Frequent 500 Backend Error

### ISSUE THREAD

**Issue by jonnenauha** [GoogleCloudPlatform/gcloud-golang#179]
I have a build bot that has been uploading go/js projects to S3. I want to move the deployments to gcloud storage due to http2 and other nice things you bring in.

The deployments are 100-400 files at a time depending on the project. Size would be ~5-8mb in total, so usually lots of small gzip compressed files. For publicly visible libs (js/html/css) that get included from web pages I gzip all data that is reasonable and set the content encoding and cache control attributes in go. This all works wonderfully.

The build bot (also built with go) does 1-10 deployments a day depending on how frequent our devs push to nightly. After about 5-15 builds I start to get a 1-5 uploads fail (from the hundreds of total uploads) with `googleapi: Error 500: Backend Error, backendError`. I have to go and restart the process and manually restart the builds, for now what I have observed the uploads always succeed after a boot. If I restart the build/uploads manually without exiting the process it usually fails from there onward, but sometimes it does succeed. So I cant definitely say after x amount of time, all uploads fail, that's not the case. The frequency of 500 errors just starts to increase. I have never seen anything but 500 error codes back.

I have a few questions:

* The error suggest this is not something my code or your lib does wrong, but a backend error. But I somehow have a hard time understanding this. Afaik gcould storage is a massive system and widely used in productions etc. Can it really be the case uploads just fail this frequently for all uploads? I would think it has to be in my code or this lib.
 * Is it a "sound strategy" to try re-upload the failed files until they succeed? (with some max retry ofc). I haven't tried this yet, but it would be trivial to add as usually number of failed files is quite low.
* I'm creating all 100-400 files to have their own `*Writer`, setup the object path/name, setup all the attributes, then send the `*Writer + []byte slice` to a channel. I have 6 uploader gorotines that execute the actual uploads, they all call `Write` and always call `Close` (so your internal goroutine should not be left alive).
 * Is there something wrong with uploading multiple files in parallel? I haven't found any docs that would suggest what is ok. I did read your code enough to see that they execute each write in a goroutine and there should be nothing preventing me from doing multiple in parallel. I started with 20, went down to 10 and then to 6 (emulating what browsers would do, max 6 TCP connections) and still get the random errors.
 * I have also ran the built bot with `-race` and it produces no warnings/dumps executing multiple builds and uploads. The bot processes one build at a time with a queue, there cant be multiple project builds/uploads at the same time (though it could do this but atm there is no need).
* As it feels that the longer the build bot runs, the more failures start to happen, does the client and/or its context need to be "refreshed" somehow? I create one client at the start of the process and use it to create new `*Writers`. For the writers I pass in the same context as for the client. I tried passing `context.Background()` but got a panic on the first operation I did. Apparently they need to get the context that was created from the project id + credentials.

I do realize this package is not officially for production use yet. I do build new version of the build bot every now and then, at that point it pulls master of your lib in as you don't yet have tags. Is there something in master that might cause these issues? Is there a commit hash that I should vendor?

A while back I made a cmd line tool that uploaded 10-200k files to google cloud during a 2-5h period. It was generating a lot off assets and pushing them to long term storage. With it I saw very low number of errors (compared to the number of uploaded files). This also used parallelism, and had way more than 6 parallel uploaders. But it was build 2-3 months ago with your master, this is why I ask about vendoring.

Sorry for the massive long desc, I wanted to explain the situation as much as I can. I don't have anything for you to reproduce or useful stack traces. I also have no idea how to test and find this failure intelligently as it starts happening usually in long running processes. This is more questions than a proper actionable bug report, hopefully that's ok here.

**Edit:** The build bot that uses your lib is currently using go 1.4.2. I'm in the process of updating the bot to build 1.5.x binaries but I havent had the time to figure our the new cross compilation. It builds all our services/apps for linux, mac and windows. Just FYI if go version makes any difference here.

**Comment by jonnenauha** [comment]
I implemented max 3 re-upload attempts per failed file. It does hit quite regularly still but the reuploads are successful. First build I spinned up with the new logic had total of 6 re-uploads but succeeded. Now that I'm confident the files will eventually get there, I pumped parallel uploads to 10, which has a big impact on the total upload time.

I think my questions are still valid
* Should the users expect such a high error rate?
* What number of parallel uploads are ok?
* Should the lib implement configurable auto retries if errors are so frequent? If not should this be documented so people realize to implement it in user code. I think everyone understands that failure is always an option when moving bytes over the network, but if the error rate starts to approach ~1/100 uploads maybe it should be noted explicitly.

**Comment by gmlewis** [comment]
Can you please privately email me the full name of the bucket you are sending the files to so that I can have Google Cloud Storage engineers investigate the logs and see if they can find any problems on their side?

**Comment by okdave** [comment]
@jonnenauha Are you still experiencing this problem? I haven't been able to repro the results you were seeing.

**Comment by jonnenauha** [comment]
I think it does still happen occasionally, if it does its in the log files that we dont really look at if no build failures happen.

I implemented upload retry with a bit of backoff between tries. If it fails 3 times it will fail the whole build, but I don't think has ever happened since I did the retry logic.

So you can close this if you wish, nothing really actionable on my "bug report". I suppose every user should know to implement retries if the uploads are critical.

**Comment by okdave** [comment]
@jonnenauha we've added automatic chunking and retry logic to the underlying API so that 500s like this shouldn't interrupt your workflow. Let us know if you keep seeing any issues.

**Comment by jonnenauha** [comment]
Thanks @okdave. I just yesterday ran some asset generation that uploaded 10k gzipped ~100kb files with 12 parallel upload goroutines and got zero responses. Your fixes were not even in that build so I would say this has been resolved along the way. Maybe during the big breaking refactor that happened a while ago.
