### ISSUE TITLE
bigtable/bttest: column family does not be checked in ReadModifyWrite

### ISSUE THREAD

**Issue by hsinhoyeh** [GoogleCloudPlatform/gcloud-golang#181]
hi,

in mutaterow, bttest will check the existance of a column family.
https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/bigtable/bttest/inmem.go#L468
```
_, famOK := tbl.families[set.FamilyName]
tbl.mu.RUnlock()
if !famOK {
    return fmt.Errorf("unknown family %q", set.FamilyName)
}
```

however, we haven't saw such check in ReadModifyWrite
https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/bigtable/bttest/inmem.go#L601

```
if f == nil {
	f = &btdpb.Family{Name: fam}
	res.Families = append(res.Families, f)
}
```
which means we allow ReadModifyWrite to operate on a non-existing column family.
Is it an expected behavior?

**Comment by dsymonds** [comment]
It's just an oversight.

**Comment by hsinhoyeh** [comment]
thanks
