### ISSUE TITLE
pubsub docs for PullWait might be inaccurate

### ISSUE THREAD

**Issue by christopherhesse** [GoogleCloudPlatform/gcloud-golang#182]
For the pubsub.PullWait docs here: https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/pubsub/pubsub.go#L225

"PullWait pulls messages from the subscription. If there are not enough messages left in the subscription queue, it will block until at least n number of messages arrive or timeout occurs, and n could not be larger than 100."

If I'm reading https://cloud.google.com/pubsub/reference/rest/v1/projects.subscriptions/pull correctly it should be:

"PullWait pulls messages from the subscription. If there are no messages available in the subscription queue, it will block until at least 1 message arrives or timeout occurs.  n can not be larger than 100."

I also don't see where the API says n cannot be more than 100 though.  The code itself seems to limit n to 1000, not 100.

I tested this with n=10 and it would return before the timeout with only 1 message in the queue, so not "at least 10 messages".  The weird part about this is that for the very first message, it seems like PullWait() did wait until the timeout, but for subsequent messages PullWait() returned as soon as the message was enqueued.   When I tried the interactive widget on: https://cloud.google.com/pubsub/reference/rest/v1/projects.subscriptions/pull the behavior seemed to be what I wrote in my description.

It's also not clear where the timeout on PullWait() is set.  Any hints on that?

**Comment by mcgreevy** [comment]
Yes, that doc comment is inaccurate.  I am doing some cleanup work on this API at the moment, and plan to address this as part of that.

You are correct that PullWait does not wait for n messages before returning.

The API does not limit the number of messages that can be requested, but the API may always return fewer messages than requested.  The client Go pubsub client library enforces a limit of 1000 (the value of "100" in the documentation is out of date).

The PullWait timeout is not user-configurable.

**Comment by christopherhesse** [comment]
Cool, thanks for letting me know!

For the initial behavior of PullWait(): I'm not sure what I'm doing wrong here.  I made two smaller test programs, "subscribe.go" and "publish.go".  I run the subscriber, which calls PullWait() then run the publisher which just publishes a message.  The first message has a delay of about 60 seconds, but subsequent messages have a very short delay (< 1 second).  Any ideas?  Here is the code: https://gist.github.com/christopherhesse/295e14d222600f43ca79

For the timeout: would it be possible to document what the value is then?

**Comment by christopherhesse** [comment]
The log from subscribe.go looks like this:

2015/10/22 22:55:20 poll
2015/10/22 22:56:22 got msg=test message: 2015-10-22 22:55:21.587426002 -0700 PDT
2015/10/22 22:56:23 acked message
2015/10/22 22:56:24 poll

What's interesting is that it *is* returned from the first call to PullWait(), it just takes the full timeout time.  
There's a 1 minute difference between when the message was published and when it got pulled.

**Comment by sairahu** [comment]
Just to add to this, there is a similar mistake in the comments for Pull() https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/pubsub/pubsub.go#L216

**Comment by christopherhesse** [comment]
A quick note to anyone trying to configure the timeout on PullWait:

According to the docs at https://cloud.google.com/pubsub/reference/rest/v1/projects.subscriptions/pull "The client may cancel the request if it does not wish to wait any longer for the response."

Using context.Context, this seems to work:

		url := fmt.Sprintf("https://pubsub.googleapis.com/v1/projects/%s/subscriptions/%s:pull", project, sub)
		buf := bytes.NewBufferString(`{"returnImmediately": false, "maxMessages": 100}`)
		tc, _ := context.WithTimeout(c, 30*time.Second)
		resp, err := ctxhttp.Post(tc, client, url, "application/json", buf)

**Comment by christopherhesse** [comment]
It looks like someone figured out the proper fix for that over here: https://github.com/GoogleCloudPlatform/gcloud-golang/issues/200

**Comment by jba** [comment]
Won't fix because PullWait is deprecated.
