### ISSUE TITLE
bigtable: Table.ReadRows with context.Background leaks goroutines

### ISSUE THREAD

**Issue by smreed** [GoogleCloudPlatform/gcloud-golang#183]
Using the latest go-grpc code (https://github.com/grpc/grpc-go/commit/1f1a4999ca75ba4fd6d5c91233383a170034a1a5), every call to `Table.ReadRows(context.Background(), ...` will leak a goroutine.

grpc recently added a goroutine for every client stream that waits on the supplied context's `Done` channel. 

`ReadRows` wraps the given `context.Context` with cancel, but only calls it if the `func(Row)` returns false.

**Comment by dsymonds** [comment]
It's something we can work around in the bigtable code, but it sounds like a bug in grpc. The bigtable code either cancels the context (if it wants to stop the stream short), or reads to the end of the RPC stream (`io.EOF` or some other error).

@iamqizhao

**Comment by smreed** [comment]
According to the `context.Context` doc, "Canceling this context releases resources associated with it, so code should call cancel as soon as the operations running in this Context complete."

I believe the context created inside of `ReadRows` should always call `cancel()` before returning.

I tested adding a `defer cancel()` to the line below where the context is created and it seemed to work well.

**Comment by dsymonds** [comment]
Yes, but if anything that's an optimisation. There shouldn't be a goroutine leak if we don't do that.

An alternate way to look at it: In the situations where we *don't* call `cancel`, the RPC is unequivocally finished. Why is gRPC keeping a dangling goroutine around in that case?

**Comment by smreed** [comment]
Agreed, receiving on a channel that can sometimes be `nil` is dangerous.

I had actually filed this originally (and accidentally) against go-grpc at https://github.com/grpc/grpc-go/issues/416.

For now I'm using a workaround of wrapping all of my `Context`s with cancel, and cancelling them after `ReadRows`. It only affected a few uses, most others are already using deadlines and those are fine.

**Comment by iamqizhao** [comment]
Can I request a reproduce to have a close look? gRPC should cancel the
context once the corresponding stream is done.

**Comment by iamqizhao** [comment]
To be clear, there is no issue in grpc/grpc-go#416
<https://github.com/grpc/grpc-go/issues/416> which has been closed.

**Comment by iamqizhao** [comment]
should be fixed by https://github.com/grpc/grpc-go/pull/418. It was due to
a a former optimization which was not applied when this new goroutine is
added.
