### ISSUE TITLE
GeoPoint can not be loaded from datastore

### ISSUE THREAD

**Issue by cnbuff410** [GoogleCloudPlatform/gcloud-golang#187]
If the defined struct has fields of type appengine.GeoPoint, "get" method will give the error message as follows:

datastore: cannot load field "Values" into a "main.LocationList": no such struct field

And all the GeoPoint data are not loaded.

Is it supported by this package? If not, any quick workaround for this?

**Comment by okdave** [comment]
Unfortunately, GeoPoint is currently not available in the current datastore API. We're awaiting a new version of the API which will support it correctly.

See #46 which is tracking this.
