### ISSUE TITLE
storage: support generation preconditions

### ISSUE THREAD

**Issue by sbaileyms** [GoogleCloudPlatform/gcloud-golang#188]
This makes it impossible to do optimistic concurrency through the storage API. I could use the lower level JsON go wrapper but that's a more complex API.

**Comment by derekperkins** [comment]
:+1: so that #146 can happen

**Comment by okdave** [comment]
A quick overview of where preconditions are supported:

The generation preconditions (if/if not generation matches and if/if not metageneration matches) applies to [the following methods](https://cloud.google.com/storage/docs/json_api/v1/objects):

- `insert`
- `delete`
- `get`
- `copy`
- `compose`
- `rewrite`
- `update`
- `patch`

(That is basically everything except `list`).

Some of the methods also have the ability to target a specific generation (ie. an older one): `get`, `copy`, `compose`, `delete`, `update`.

`copy`, `rewrite` and `compose` allow you to set preconditions on both the source and destination objects. `compose` does not support the "if not" matches, and doesn't support metagenerations for the source objects.
