### ISSUE TITLE
bigquery: no streaming api to load data from memory

### ISSUE THREAD

**Issue by 4shome** [GoogleCloudPlatform/gcloud-golang#189]
Both the python / java version have this api..
This force me to use https://github.com/google/google-api-go-client, which looks ugly.
Which library do you expect people to use?

**Comment by 4shome** [comment]
Any updates on this issue?

**Comment by mcgreevy** [comment]
I have a partial implementation of this, but it's not quite ready to be checked in.  It will probably appear a couple of weeks from now.

**Comment by 4shome** [comment]
Thanks for the quick update! Looking forward to that.

**Comment by dhowden** [comment]
Anything further on this? I want to use this soon and in the worst case can probably make time to implement it (if you are are open to contributions of this size).

**Comment by mcgreevy** [comment]
Sorry for the delay; some other issues came up which pushed this work out. I expect it will be another week or two.

**Comment by dhowden** [comment]
Any progress on this? Cheers.

**Comment by mcgreevy** [comment]
I appreciate the continued interest in this feature.  I'm actively working on it and look forward to getting it checked in some time in the next week.

**Comment by mcgreevy** [comment]
Please sync to HEAD and try out the streaming upload support.  Let me know what you think of it.
