### ISSUE TITLE
bttest ReadRows interval 

### ISSUE THREAD

**Issue by tartavull** [GoogleCloudPlatform/gcloud-golang#190]
https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/bigtable/bttest/inmem.go#L250

Shouldn't   `ei` be `ei - 1` ?

**Comment by dsymonds** [comment]
`start`/`end` is a half-open interval, which means that `end` should be excluded. That line computing `ei` is finding the first index `>= end` as part of computing the half-open index interval `si`/`ei`, so it's correct as is.
