### ISSUE TITLE
storage.NewClient requires Scope to be usable

### ISSUE THREAD

**Issue by dustin** [GoogleCloudPlatform/gcloud-golang#192]
This doesn't seem to be mentioned in the docs and is not shown in the examples, but if a scope is not included somehow in the `storage.NewClient` call, it fails `API error 9 (app_identity_service: UNKNOWN_SCOPE)`.

Running the AppEngine example code produces the same results.

The documented example shows the scope being passed in via `cloud.WithTokenSource` which won't apply to AppEngine usage.  I was able to sort this out eventually by guessing there were other parameters available to `NewClient` that I could find in the [google.golang.org/cloud](https://godoc.org/google.golang.org/cloud) package that would sort things out, which led me to the following:  `storage.NewClient(c, cloud.WithScopes(storage.ScopeReadWrite))`

I suppose at some point that was implied, but the error was only barely helpful and the docs and examples were misleading.  It'd be good if the following were done:

* `cloud.WithScopes` mentioned in the API docs (e.g. what the included scopes are for)
* AppEngine example in the docs showing `cloud.WithScopes`
* Update executable example to work (perhaps run as integration test)
* Try to stuff something into the log message indicating a scope wasn't specified.
* Perhaps default to a read-write scope if the user doesn't specify one -- this seems like the least surprising thing for someone making a client and attempting to write with it.

**Comment by dustin** [comment]
Thanks!

**Comment by broady** [comment]
Oddly enough, even without the default scope being set, the integration test ran successfully. Perhaps there's something else going on with the service accounts?

**Comment by dustin** [comment]
It definitely didn't work for me.  I'm not sure what the difference is.
It's possible I was picking up some older appengine code.  I had just
downloaded the latest sdk, and statting around, I don't see anything older
than a couple of days ago in $GOPATH/src/google.golang.org

**Comment by broady** [comment]
oh, I meant *outside* of App Engine, everything works, but I would not expect it to.

**Comment by dustin** [comment]
Oh, ha.  Yeah, I've only used inside so far.  I've got more use cases now
that I've started using Cloud Storage, though.

For this particular thing, we're collecting breakpad crashes in the wild.
I'm probably going to end up storing symbol tables out of the builders
(possibly directly to Cloud Storage) as well as needing to run analysis.
