### ISSUE TITLE
logging: ping isn't rejecting missconfigured requests 

### ISSUE THREAD

**Issue by mikedanese** [GoogleCloudPlatform/gcloud-golang#198]
This integration test would fail currently:
```
var (
        projID = testutil.ProjID()
        ctx    = testutil.Context()
)

func TestMissconfiguredPingFails(t *testing.T) {
        var (
                c   *logging.Client
                err error
        )

        if c, err = logging.NewClient(ctx, projID+"-bad-project-name", "logging-integration-test"); err != nil {
                t.Fatalf("error creating client: %v", err)
        }

        if err := c.Ping(); err == nil {
                t.Fatalf("expecting Ping() error for misconfigured client.")
        }
}
```

**Comment by jba** [comment]
We're working on a new version of the logging client that won't have Ping. What's your use case for Ping?

**Comment by mikedanese** [comment]
@jba it was to verify the client configuration. With the current logging client, I can create a client, configure it, and not know if it is able to authenticate or authorized to write logs until my first log write. As ping is currently documented:

> Ping reports whether the client's connection to Google Cloud Logging and the authentication configuration are valid.

This is not what it does. There is currently no way to fail fast if a logging client is misconfigured.

**Comment by broady** [comment]
@jba definitely a use case for this. you want to fail in `init()` if anything is misconfigured. We should have something like this in the new logging client.

**Comment by jba** [comment]
@broady Fine, but wouldn't this also be true for all other clients?

**Comment by broady** [comment]
It's fine for most APIs to fail on the first call. Logging is a bit different since the logs are sent asynchronously. So the first call may appear to work, but the log entry is only sent later on.

I suppose you could log an entry synchronously just to test auth.

**Comment by jba** [comment]
The problem with the current implementation of Ping is that it works by calling WriteLogEntries with an empty list of entries, and the logging service treats that as a no-op, with no checks. I'm working on a new implementation.
