### ISSUE TITLE
storage: no way to fetch object's content & size in one HTTP request

### ISSUE THREAD

**Issue by bradfitz** [GoogleCloudPlatform/gcloud-golang#199]
Migrating Camlistore to the official google.golang.org/cloud/storage package (away from our own old package), we found that there's no way to get a Reader of the contents of an object and its metadata (specifically its size, but also content-type) in one HTTP request.

I think instead of returning an interface here:
https://godoc.org/google.golang.org/cloud/storage#ObjectHandle.NewReader

... it should return a `*Reader` which is a ReadCloser itself, but also is a struct where we can attach metadata from the server's HTTP response headers.

/cc @mpl @okdave

**Comment by bradfitz** [comment]
For now we'll put our own implementation of `NewReader` in https://godoc.org/go4.org/cloud/google/gcsutil for now, until the official package can do it.

**Comment by broady** [comment]
https://code-review.googlesource.com/3977
