### ISSUE TITLE
pubsub: cancelling a PullWait

### ISSUE THREAD

**Issue by kidoman** [GoogleCloudPlatform/gcloud-golang#200]
Looking at the generated APIs, it looks like calling the `Context()` method of the underlying `ProjectsSubscriptionsPullCall` would do the right thing (by internally using `ctxhttp.Do`).

What is the recommended approach to cancelling a `PullWait` currently?

**Comment by kidoman** [comment]
After looking at the other clients, it seems that adding a `Context(ctx)` on the returned `ProjectsSubscriptionsPullCall` would do the trick

**Comment by christopherhesse** [comment]
I tried this and while it's great for a one-time listener, it might be nice to make it apparent that you don't want to run it in a loop.  Since the request is only cancelled on the client side, the server will still send some messages to the client which will not receive them.

**Comment by mcgreevy** [comment]
PullWait is now deprecated.  The equivalent in the new API is calling Next on an Iterator. This can be cancelled by calling Stop on the Iterator.
