### ISSUE TITLE
datastore: ScopeUserEmail documentation

### ISSUE THREAD

**Issue by bradfitz** [GoogleCloudPlatform/gcloud-golang#201]
The docs at https://godoc.org/google.golang.org/cloud/datastore say:

```
    // ScopeUserEmail grants permission to view the user's email address.
    // It is required to access the datastore.
    ScopeUserEmail = "https://www.googleapis.com/auth/userinfo.email"
```

Whose email?

And which scope do I want? Both?

**Comment by broady** [comment]
ScopeUserEmail no longer required.

7df4f4f

https://code-review.googlesource.com/#/c/4480/
