### ISSUE TITLE
storage: documentation error on ObjectHandle.NewWriter

### ISSUE THREAD

**Issue by bradfitz** [GoogleCloudPlatform/gcloud-golang#204]
> func (o *ObjectHandle) NewWriter(ctx context.Context) *Writer
> NewWriter returns a storage Writer that writes to the GCS object identified by the specified name.

"specified name" is an old artifact. It's now part of o.

**Comment by okdave** [comment]
I'm fixing NewWriter a bit more broadly in https://code-review.googlesource.com/#/c/4024/ – does the updated comment there look okay?
