### ISSUE TITLE
datastore: Support the DATASTORE_HOST environment variable

### ISSUE THREAD

**Issue by dlorenc** [GoogleCloudPlatform/gcloud-golang#205]
Other GCP client libraries support the DATASTORE_HOST environment variable for overriding the address of the datastore instance to connect to, which is particularly useful for connecting to a local instance of the datastore emulator for testing.

See here for how the python library handles this:
https://github.com/GoogleCloudPlatform/gcloud-python/blob/896044579b5dfaddb75e8c7cbf72b614b0d04c5e/gcloud/datastore/connection.py#L61

**Comment by broady** [comment]
https://code-review.googlesource.com/#/c/3350/

**Comment by broady** [comment]
@okdave can you take another look at that CL? I think the pending question was about that sentinel value

**Comment by okdave** [comment]
Done. Mostly good. :D

**Comment by dlorenc** [comment]
Friendly ping. Is there anything I can do to help unblock that CL?

**Comment by broady** [comment]
merged here: 8bc2457bef5a52c10b0001d481d441141095b130
