### ISSUE TITLE
pubsub: Support the PUBSUB_HOST environment variable

### ISSUE THREAD

**Issue by dlorenc** [GoogleCloudPlatform/gcloud-golang#206]
Similar to #205, but for Pub Sub.
Other GCP client libraries support the PUBSUB_HOST environment variable for overriding the address of the pubsub instance to connect to, which is particularly useful for connecting to a local instance of the pubsub emulator for testing.

See here for how the node library handles this:
https://github.com/GoogleCloudPlatform/gcloud-node/blob/36a9f5c931a8d5f6fa566205cccae71ba99b79d5/lib/pubsub/index.js#L86

**Comment by broady** [comment]
https://code-review.googlesource.com/#/c/4340

**Comment by dlorenc** [comment]
Thanks Chris!

**Comment by hbchai** [comment]
Thanks for implementing this! Does the code currently pass on default app credentials to the emulator? If so, we should change it to not do that. (Sorry for my ignorance regarding how this works in Go.)

**Comment by broady** [comment]
@hbchai see #280

**Comment by hbchai** [comment]
Thanks @broady !
