### ISSUE TITLE
bigtable: client does not support batched writes

### ISSUE THREAD

**Issue by dhruv** [GoogleCloudPlatform/gcloud-golang#211]
Is this a conscious decision, or are we just waiting for the roadmap to play out? Could you help me understand the priority for this?

cc: @MrTravisB

**Comment by dsymonds** [comment]
The underlying RPC API didn't originally support bulk operations at all. I believe there's a recent change to support them, but I haven't checked whether that's available yet.

**Comment by dhruv** [comment]
Thank you! We will watch the release notes and wait for this change.

**Comment by dhruv** [comment]
@dsymonds Do you happen to know if there's any update on this?

**Comment by garye** [comment]
@dhruv I'm currently working on this change, should be ready soon. I'll reply here when it's available.

**Comment by dhruv** [comment]
Thank you -- quick question about it: Will the batch writes have to be to the same table?

**Comment by garye** [comment]
@dhruv Yes, batch writes are applied to a single table (but across row keys).

**Comment by garye** [comment]
This has been released: https://cloud.google.com/bigtable/docs/go/reference#Table.ApplyBulk

**Comment by dhruv** [comment]
Thank you for the notification, Gary.
