### ISSUE TITLE
datastore: datastore/example_test.go example functions return 401 invalid credentials

### ISSUE THREAD

**Issue by randall2602** [GoogleCloudPlatform/gcloud-golang#212]
This example function returns a 401 invalid credentials error when run on a Google Compute Engine instance running in a project that has the datastore API enabled and a JSON key generated.

    func Example_auth() *datastore.Client {
        // Initialize an authorized context with Google Developers Console
        // JSON key. Read the google package examples to learn more about
        // different authorization flows you can use.
        // http://godoc.org/golang.org/x/oauth2/google
        jsonKey, err := ioutil.ReadFile("/path/to/json/keyfile.json")
        if err != nil {
            log.Fatal(err)
        }
        conf, err := google.JWTConfigFromJSON(
            jsonKey,
            datastore.ScopeDatastore,
            datastore.ScopeUserEmail,
        )
        if err != nil {
            log.Fatal(err)
        }
        ctx := context.Background()
        client, err := datastore.NewClient(ctx, "project-id", cloud.WithTokenSource(conf.TokenSource(ctx)))
        if err != nil {
            log.Fatal(err)
        }
        // Use the client (see other examples).
        return client
    }

**Comment by 4shome** [comment]
I have a similar problem. I run it from managed VM using the default credential.

**Comment by 4shome** [comment]
I solved my problem. It was caused I didn't run gcloud init for the user I run my job (only did that for my own account). It would be nice if the code could print some useful info for such cases.

**Comment by andrewwatson** [comment]
i have the same problem but i suspect it's because the key i'm using belongs to a service account that doesn't have Editor permissions

**Comment by jba** [comment]
@andrewwatson assuming you're right and closing this.
