### ISSUE TITLE
undefined: http2.TrailerPrefix

### ISSUE THREAD

**Issue by ruiyang2015** [GoogleCloudPlatform/gcloud-golang#214]
I am getting this error for the latestvendor/google.golang.org/grpc/transport/handler_server.go:202: undefined: http2.TrailerPrefix
this is from the latest head of master. 
I did a clean glide get golang.org/x/net/http2 and still get this error.

**Comment by bradfitz** [comment]
No, somehow you have an old version still. Not sure what you did, though.
