### ISSUE TITLE
pubsub: when will pubsub.NewClient respect JSON credentials

### ISSUE THREAD

**Issue by willie** [GoogleCloudPlatform/gcloud-golang#215]
```
	data, err := ioutil.ReadFile(*confPath)
	if err != nil {
		log.Fatal(err)
	}
	conf, err := google.JWTConfigFromJSON(data, "https://www.googleapis.com/auth/pubsub")
	if err != nil {
		log.Fatal(err)
	}
	ctx := cloud.NewContext(*projID, conf.Client(oauth2.NoContext))

	ps, err := pubsub.NewClient(ctx, *projID)
	if err != nil {
		log.Fatal("new client:", err)
	}

```
results in: 

> new client:dialing: google.DefaultTokenSource: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

While the older, deprecated code for initializing and using pubsub.Pull works just fine. The example code seems to skirt by this as well, only doing JSON auth for the "olderStyle" path in https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/examples/pubsub/cmdline/main.go

Any idea when this will get fixed?

**Comment by mcgreevy** [comment]
Hi @willie, you can use JSON credentials with NewClient by passing in a cloud.ClientOption returned by cloud.WithTokenSource e.g, in your example:

    data, err := ioutil.ReadFile(*confPath)
    if err != nil {
        log.Fatal(err)
    }
    conf, err := google.JWTConfigFromJSON(data, "https://www.googleapis.com/auth/pubsub")
    if err != nil {
        log.Fatal(err)
    }
    ctx := context.Background()
    ts := conf.TokenSource(ctx)
    ps, err := pubsub.NewClient(ctx, *projID, cloud.WithTokenSource(ts))
    if err != nil {
        log.Fatal("new client:", err)
    }

Let me know if you have any further issues with this.

**Comment by willie** [comment]
That worked! Thanks. Have you all considered leaving the older Pull/Ack in place, as it seems to be more efficient if you do large pulls at a time.

**Comment by mcgreevy** [comment]
Can you give me some more details about what seems less efficient about the new API?

**Comment by willie** [comment]
I have a little benchmark test I wrote in Go while evaluating PubSub and the old API seems to be 2X faster if you use pulls and acks of 100 at a time vs. the new iterator style. Probably doesn't matter, but there you go.

**Comment by mcgreevy** [comment]
The new iterator style fetches batches of 100 under the hood (this will probably be made more dynamic or configurable, but that's what it's doing right now).  The acking is also batched, but the details of that might differ a bit more compared with how you are doing it.

If you are willing to share your benchmark code (and also the default ack deadline of the subscription you are pulling from), I'd be interested in looking into what's causing the performance difference that you are seeing.

**Comment by willie** [comment]
I will. (As soon as I finish my battle with the Datastore interface.)

**Comment by alanma** [comment]
Hi @mcgreevy

Am trying out the service account oauth2 code you shared above. I could call the pubsub APIs locally without using GAE devappserver; however, when running local devappserver or deployed to GAE, I got the following error when making pubsub calls:

```oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: not an App Engine context```

I could not figure out what's not right. I'm using Go Appengine SDK 1.9.35.

Thanks in advance.

**Comment by alanma** [comment]
@willie have you tried deploying the oauth2 service account sample on GAE? thanks.
