### ISSUE TITLE
storage: Writer always truncates files on close

### ISSUE THREAD

**Issue by toqueteos** [GoogleCloudPlatform/gcloud-golang#219]
Reference: https://github.com/GoogleCloudPlatform/gcloud-golang/pull/218

Quoted from [GoDoc's ObjectHandle.NewWriter](https://godoc.org/google.golang.org/cloud/storage#ObjectHandle.NewWriter):

>  NewWriter returns a storage Writer that writes to the GCS object associated with this ObjectHandle. If such an object doesn't exist, it creates one. Attributes can be set on the object by modifying the returned Writer's ObjectAttrs field before the first call to Write.

> It is the caller's responsibility to call Close when writing is done.

> The object is not available and any previous object with the same name is not replaced on Cloud Storage until Close is called. 

I propose adding a brief explanation of what happens when objects do already exist as there's no way, that I'm aware of, for opening a file for writing without truncating it.

/cc @bradfitz

**Comment by bradfitz** [comment]
GCS is not a POSIX filesystem. It's true you can't do random writes inside objects, nor open an object for read+write.

We can probably add a bit more text.

**Comment by nightlyone** [comment]
It actually is explained rather well at https://cloud.google.com/storage/docs/key-terms on bullet point "Object immutability" and inter-operation behavior at https://cloud.google.com/storage/docs/consistency so linking to this might suffice.
