### ISSUE TITLE
fails on appengine dev due to http2/grpc dependency

### ISSUE THREAD

**Issue by dakom** [GoogleCloudPlatform/gcloud-golang#220]
Using latest appengine SDK which is go version 1.4.2 under the hood:

`go get google.golang.org/grpc` fails due to dependency on http2 which evidently doesn't work with the current appengine sdk release. Seems http2 stuff is only available only from 1.6+:

> from Go 1.6 and later

(ref: https://godoc.org/golang.org/x/net/http2)

calling `go get golang.org/x/net/http2` did not fix the errors

While I originally caught this in working with gcs, seems it's used throughout this library:  https://github.com/GoogleCloudPlatform/gcloud-golang/search?utf8=%E2%9C%93&q=grpc

**Comment by dsymonds** [comment]
In what way does it fail?

**Comment by bradfitz** [comment]
I verified I'm able to install grpc and http2 with Go 1.4.2.

**Comment by dakom** [comment]
Strange... setting a new GOPATH and trying from there fixed it. Not a coding problem but something wacky in my local configuration. Thanks for looking into it anyway :dancers:

**Comment by dakom** [comment]
Just for the record...

**davidk-osx:Desktop davidk$ more ~/.bash_profile**

> export GOROOT=/usr/local/go
> export PATH=$PATH:$GOROOT/bin
> export GOPATH=/Users/davidk/Documents/golang
> export PATH=$GOPATH/bin:$PATH

**davidk-osx:Desktop davidk$ go version**

> go version go1.6 darwin/amd64

**davidk-osx:Desktop davidk$ /Applications/go_appengine/goapp version**

> go version go1.4.2 (appengine-1.9.33) darwin/amd64

**davidk-osx:Desktop davidk$ mkdir ./TEMP_GOPATH**
**davidk-osx:Desktop davidk$ export GOPATH=/Users/davidk/Desktop/TEMP_GOPATH**
**davidk-osx:Desktop davidk$ go get google.golang.org/grpc**
**davidk-osx:Desktop davidk$ go get google.golang.org/cloud/storage**

(i.e. everything is fine, but then...)

**davidk-osx:Desktop davidk$ export GOPATH=/Users/davidk/Documents/golang**
**davidk-osx:Desktop davidk$ go get google.golang.org/grpc**

> \# google.golang.org/grpc/transport
> ../Documents/golang/src/google.golang.org/grpc/transport/http2_client.go:678: undefined: http2.MetaHeadersFrame
> ../Documents/golang/src/google.golang.org/grpc/transport/http2_client.go:774: undefined: http2.MetaHeadersFrame
> ../Documents/golang/src/google.golang.org/grpc/transport/http2_server.go:140: undefined: http2.MetaHeadersFrame
> ../Documents/golang/src/google.golang.org/grpc/transport/http2_server.go:253: undefined: http2.MetaHeadersFrame
> ../Documents/golang/src/google.golang.org/grpc/transport/http_util.go:279: f.fr.ReadMetaHeaders undefined (type *http2.Framer has no field or method ReadMetaHeaders)
> davidk-osx:Desktop davidk$

**Comment by aeijdenberg** [comment]
FYI I had the same problem, and was able to clear it by running "go get -u all" to update my other Go packages, and then was able to successfully run "go get" on the PubSub library.

**Comment by zhangshengshan** [comment]
@dakom 
`go get -u golang.org/x/net/http2 `
http2 need to be updated, and the command above could help
