### ISSUE TITLE
datastore: support for gRPC v1beta3

### ISSUE THREAD

**Issue by mwitkow** [GoogleCloudPlatform/gcloud-golang#225]
Hey,

I've found the new gRPC based proto definitions for Datastore hanging around in the Google APIs repo:
https://github.com/googleapis/googleapis/tree/master/google/datastore/v1beta3

This is pretty exciting, since gRPC brings in HTTP2 multiplexing which would save us *a ton* of reconnecting from our servers in GCE to Datastore.

Any roadmap update when this'll be available in the gcloud-golang? :)

**Comment by bradfitz** [comment]
You can use the non-gRPC API over HTTP2 too. Just use Go 1.6+ (where it's automatic), or use a https://godoc.org/golang.org/x/net/http2#Transport with the datastore package.

**Comment by mwitkow** [comment]
@bradfitz that's precisely what I did :)

It would still be awesome to have gRPC client though :) Hopefully using the new gRPC interface over the RESTful one bring in other benefits ;)
