### ISSUE TITLE
pubsub: allow setting iterator batch size

### ISSUE THREAD

**Issue by cameront** [GoogleCloudPlatform/gcloud-golang#226]
Love the new iterator pattern - but the inability to fetch fewer messages per pull (aka this [TODO](https://github.com/GoogleCloudPlatform/gcloud-golang/blob/ab6762587120f590adf808437a5819b991ac2d20/pubsub/iterator.go#L26)) is problematic for our use case. 

We have some long-running jobs that we're trying to shard among several machines. Without the ability to make the batch size 1, the first puller hogs all the messages, and the remaining machines sit idle.

We could just fork and make that batchSize field settable, but if there were plans/ideas to address this soon I'd be happy to wait a bit.

Thanks!

**Comment by mcgreevy** [comment]
Hi @cameront,

Thanks for the request.  I've just sent out https://code-review.googlesource.com/4351 for review.  Hopefully it addresses your needs.

**Comment by cameront** [comment]
Welp - that was amazing. :) Thanks!
