### ISSUE TITLE
storage: ACL doesn't set properly

### ISSUE THREAD

**Issue by derekperkins** [GoogleCloudPlatform/gcloud-golang#228]
I'm trying to write public objects to GCS but it doesn't set the acl properly.

```
b := client.Bucket(bucket)
dest := b.Object(path)
acl := dest.ACL()
acl.Set(c, storage.AllUsers, storage.RoleReader)
acl.Set(c, ProjectOwners, storage.RoleOwner)
acl.Set(c, ProjectEditors, storage.RoleOwner)
acl.Set(c, ProjectViewers, storage.RoleReader)
```
When I check the file after it is written, this is the ACL returned by `gsutil`
```
gsutil acl get gs://bucket/path.json.gz
[
  {
    "entity": "project-owners-111",
    "projectTeam": {
      "projectNumber": "111",
      "team": "owners"
    },
    "role": "OWNER"
  },
  {
    "entity": "project-editors-111",
    "projectTeam": {
      "projectNumber": "111",
      "team": "editors"
    },
    "role": "OWNER"
  },
  {
    "entity": "project-viewers-111",
    "projectTeam": {
      "projectNumber": "111",
      "team": "viewers"
    },
    "role": "READER"
  },
  {
    "entity": "user-111",
    "entityId": "111",
    "role": "OWNER"
  }
]
```
It's like it completely ignored the public settings option. There aren't many docs, so maybe I'm just using it wrong, but this is how it seems like I should use it.

**Comment by bradfitz** [comment]
Two quick notes: you didn't check the error values from your Set calls, and you didn't specify what you expected to see from gsutil.

**Comment by bradfitz** [comment]
Ping, @derekperkins. Please clarify.

**Comment by derekperkins** [comment]
That's my bad for not reading the docs properly. My misconception was that I was setting them on the object handle and it was all being written out together. My workaround was to set the default bucket ACL and comment out that code. I'll try it out this weekend to see what errors are being returned.
