### ISSUE TITLE
From the (failed) gRPC build logs: "../../../cloud/compute/metadata/metadata.go:191: req.Cancel undefined (type *http.Request has no field or method Cancel)"

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [GoogleCloudPlatform/gcloud-golang#231]
(My apologies for this incomplete report; our Go engineer is away from work duties at the moment.)

As of yesterday grpc-go began failing to build with the following error:

```
../../../cloud/compute/metadata/metadata.go:191: req.Cancel undefined (type *http.Request has no field or method Cancel)
```

. We have [two](https://github.com/grpc/grpc/issues/5949) [bugs](https://github.com/grpc/grpc-go/issues/603) on the gRPC side. Even though this is a sparse report does it trigger anything obvious to you? Either assessment or action to be taken?

**Comment by broady** [comment]
See #230. Update to the latest version. Fixed in eb47ba841d53d93506cfbfbc03927daf9cc48f88.

**Comment by nathanielmanistaatgoogle** [comment]
Thanks for the response.

**Comment by broady** [comment]
Also see https://github.com/grpc/grpc-go/pull/604
