### ISSUE TITLE
storage.SignedURL and SignatureDoesNotMatch

### ISSUE THREAD

**Issue by lukef** [GoogleCloudPlatform/gcloud-golang#232]
Ok. I searched the old issues and I **swear** I am following the instructions [here](https://godoc.org/google.golang.org/cloud/storage).

Namely the following command: `$ openssl pkcs12 -in key.p12 -passin pass:notasecret -out key.pem -nodes` to generate / use a PEM for a service account P12.

Any signed url generated via `gsutil signurl` works fine, but anything via Go has a mismatch. I tested that the PEM is getting loaded correctly and have tried recreating keys / service accounts, etc. I tried using the default service accounts as well as newly created accounts.

Code: 

```go
bucketName := "bucket"
fileName := "image.jpeg"
pemBytes, _ := ioutil.ReadFile("keys/key.pem")
timestamp := time.Now().Add(time.Hour * 4)
signOpts := &storage.SignedURLOptions{
  GoogleAccessID: "xx@ppp.iam.gserviceaccount.com",
  Method:         "GET",
  ContentType:    "image/jpeg",
  Expires:        timestamp,
  PrivateKey:     pemBytes,
}
finalURL, _ := storage.SignedURL(bucketName, filename, signOpts)
```

Any help / tips appreciated.

**Comment by lukef** [comment]
Turns out I didn't fully read the source comments. I'll leave this here for other people.

A value specified in `ContentType` represents the content type header the client **MUST** provide to use the generated signed URL. After providing that header it works.

Sorry for the noise.

**Comment by lukef** [comment]
I don't know why you're assigning a ticket to me that I closed nearly 4 years ago. I am not intending to do anything with this.

**Comment by codyoss** [comment]
@lukef Apologies for the noise, a script got overzealous.
