### ISSUE TITLE
travis: run tests with -race

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/gcloud-golang#237]
We should run the tests with the race detector turned on.

I'm not sure whether we should run the tests once or twice, though, and whether we want the integration tests to run with the race detector turned on.

**Comment by okdave** [comment]
Maybe `-race -short` would be a reasonable combo so we only trigger the non-integration tests in race mode?

**Comment by shantuo** [comment]
Working on this, fixing tests failing under race mode before switch it on.

**Comment by rakyll** [comment]
With the race flag, the integration tests complete in a reasonable amount of time on my MBP.

```
$ time go test -v -race cloud.google.com/go/... 
go test -v -race cloud.google.com/go/...  131.88s user 22.00s system 150% cpu 1:42.22 total
```

**Comment by okdave** [comment]
That makes sense actually: the integration test timing is dominated by network.
