### ISSUE TITLE
Support the Google Cloud Vision API

### ISSUE THREAD

**Issue by ryanseys** [GoogleCloudPlatform/gcloud-golang#239]
Would be great if this library supported the Google Cloud Vision API: https://cloud.google.com/vision/

Until support is available, are there any suggested Go libraries for interacting with this API?

**Comment by ryanseys** [comment]
Oh I found this: https://godoc.org/google.golang.org/api/vision/v1

**Comment by broady** [comment]
Sample:
https://github.com/GoogleCloudPlatform/cloud-vision/blob/master/go/label/label.go

**Comment by ryanseys** [comment]
Thanks @broady :smile:
