### ISSUE TITLE
storage: HTTP 416 on GET request of 0 length file

### ISSUE THREAD

**Issue by kjlubick** [GoogleCloudPlatform/gcloud-golang#242]
I have a gs bucket with several 0 length files in it.  When I try to use the storage api, I get 
```Get https://storage.googleapis.com/bucket/zero-length-file: HTTP request failed inspite of exponential backoff: Got non server error statuscode 416 while making the HTTP GET request to https://storage.googleapis.com/bucket/zero-length-file```

This has started happening recently.  It works fine on any other file I try.

**Comment by okdave** [comment]
416 is `http.StatusRequestedRangeNotSatisfiable` so that makes a bit of sense.

I'll take a look.

**Comment by okdave** [comment]
OK, so GCS is doing the right thing. We're asking for the range `0-` which is valid, but since there isn't at least 1 byte that satisfies it, GCS is obliged to respond with a 416.

> If a syntactically valid byte-range-set includes at least one byte- range-spec whose first-byte-pos is less than the current length of the entity-body, or at least one suffix-byte-range-spec with a non- zero suffix-length, then the byte-range-set is satisfiable. Otherwise, the byte-range-set is unsatisfiable. If the byte-range-set is unsatisfiable, the server SHOULD return a response with a status of 416 (Requested range not satisfiable). Otherwise, the server SHOULD return a response with a status of 206 (Partial Content) containing the satisfiable ranges of the entity-body.

This should be easy enough to fix.
