### ISSUE TITLE
`go get google.golang.org/cloud/datastore` is failing

### ISSUE THREAD

**Issue by lgarron** [GoogleCloudPlatform/gcloud-golang#246]
A regression from [this Travis CI run](https://travis-ci.org/chromium/hstspreload/builds/124055089) to [this Travis CI run](https://travis-ci.org/chromium/hstspreload/builds/124058360) about an hour ago.

    # google.golang.org/cloud/datastore/internal/proto
    ../../../google.golang.org/cloud/datastore/internal/proto/datastore.pb.go:1128: cannot use _Datastore_Lookup_Handler (type func(interface {}, context.Context, func(interface {}) error) (interface {}, error)) as type grpc.methodHandler in field value
    ../../../google.golang.org/cloud/datastore/internal/proto/datastore.pb.go:1132: cannot use _Datastore_RunQuery_Handler (type func(interface {}, context.Context, func(interface {}) error) (interface {}, error)) as type grpc.methodHandler in field value
    ../../../google.golang.org/cloud/datastore/internal/proto/datastore.pb.go:1136: cannot use _Datastore_BeginTransaction_Handler (type func(interface {}, context.Context, func(interface {}) error) (interface {}, error)) as type grpc.methodHandler in field value
    ../../../google.golang.org/cloud/datastore/internal/proto/datastore.pb.go:1140: cannot use _Datastore_Commit_Handler (type func(interface {}, context.Context, func(interface {}) error) (interface {}, error)) as type grpc.methodHandler in field value
    ../../../google.golang.org/cloud/datastore/internal/proto/datastore.pb.go:1144: cannot use _Datastore_Rollback_Handler (type func(interface {}, context.Context, func(interface {}) error) (interface {}, error)) as type grpc.methodHandler in field value
    ../../../google.golang.org/cloud/datastore/internal/proto/datastore.pb.go:1148: cannot use _Datastore_AllocateIds_Handler (type func(interface {}, context.Context, func(interface {}) error) (interface {}, error)) as type grpc.methodHandler in field value
    The command "go get google.golang.org/cloud/datastore" failed and exited with 2 during .

I am able to repro on a (Goobuntu) workstation.

**Comment by dsymonds** [comment]
Fixed by 4240966.

**Comment by lgarron** [comment]
It's working again. Thanks! :-)
