### ISSUE TITLE
GAE Deployed Pubsub OAuth2 Error: oauth2/token: not an App Engine context

### ISSUE THREAD

**Issue by alanma** [GoogleCloudPlatform/gcloud-golang#248]
This might be related to https://github.com/GoogleCloudPlatform/gcloud-golang/issues/215

Am trying out the service account oauth2 code @mcgreevy shared in the above issue.

```
jsonKey, err := ioutil.ReadFile(*confPath)
    if err != nil {
        log.Fatal(err)
    }

    conf, err := google.JWTConfigFromJSON(jsonKey, pubsub.ScopePubSub, pubsub.ScopeCloudPlatform)
    if err != nil {
        log.Fatal(err)
    }
    ctx := context.Background()
    ts := conf.TokenSource(ctx)
    c, err := pubsub.NewClient(ctx, projectId, cloud.WithTokenSource(ts))
    if err != nil {
        log.Fatal("new client:", err)
    }
```

I could call the pubsub APIs locally without using GAE devappserver; however, when running **local GAE devappserver or deployed to GAE**, I got the following error when making pubsub calls:

```oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: not an App Engine context```

I could not figure out what's not right. I'm using Go Appengine SDK 1.9.35. Please help.

Thanks in advance.

**Comment by andrewwatson** [comment]
you're getting that error, i believe, because you're calling context.Background() instead of appengine.NewContext()

**Comment by dsymonds** [comment]
Yes, that'll cause it. Use appengine.NewContext(r) to get a valid context.
