### ISSUE TITLE
storage: on *ObjectHandle.Delete, return storage.ErrObjectNotExist ?

### ISSUE THREAD

**Issue by mpl** [GoogleCloudPlatform/gcloud-golang#249]
It looks like operations on an *ObjectHandle such as Attrs, NewReader, and Update return storage.ErrObjectNotExist when the object is not found, but Delete does not.

If that is correct, it is then pretty inefficient to implement functions that accept removal of non-existent objects because it requires confirming the kind of error with a subsequent call to e.g. Attr.

Or one could look for the "Error 404" part of the error message returned by Delete, but that is gross.

Am I missing something?

If not, would a CL to fix that be welcome?

**Comment by okdave** [comment]
A CL to convert to `ErrObjectNotExist` would be most welcome! See CONTRIBUTING.md for details if you need them.

**Comment by bradfitz** [comment]
I can take this.

**Comment by bradfitz** [comment]
https://code-review.googlesource.com/4630

But untested, because I'm away from a fast connection with the right credentials.
