### ISSUE TITLE
bigtable: provide a simpler "Hello World" example

### ISSUE THREAD

**Issue by hegemonic** [GoogleCloudPlatform/gcloud-golang#251]
A Cloud Bigtable engineer suggested that it would be useful to have a very simple "hello world" example for Bigtable, in addition to the more complex search example. The Go "hello world" example could be modeled after the [Java "hello world" example](https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/master/java/hello-world).

**Comment by rameshdharan** [comment]
This is fixed by 9e4a5900c09f149c2eb33b8d0cf666918f802a8f.
