### ISSUE TITLE
Can't set noindex on list properties

### ISSUE THREAD

**Issue by selfcontained** [GoogleCloudPlatform/gcloud-golang#256]
With the latest version of the datastore library it doesn't seem possible to set `noindex` on a property that is in a slice.  For example, if I have the following Struct I'm saving:

```go
type Meta struct {
	Config  []MetaConfig
}

type BotMetaConfig struct {
	Name         string
	Value        string `datastore:",noindex"`
}
```

I get an error when trying to save this:

```
code = 3 desc = Exclude from indexes cannot be set on a list value
```

I can remove that `noindex`, but now I can no longer save any value > 1500 characters, or I get the following:

```
code = 3 desc = The value of property "Config.Value" is longer than 1500 bytes.
```

Setting `noindex` on a list value used to be possible in previous versions.  In combing through some history, this commit: https://github.com/GoogleCloudPlatform/gcloud-golang/commit/8e172451ca67fecbe20890ed512199f2a8b71af2#diff-534f56f5bae9af8a4b38e5de2e2b1ea1 looks related.  I don't have a deep understanding of the library, so I could be wrong, but in case it's helpful I thought I'd mention it.

**Comment by selfcontained** [comment]
Curious if this has been viewed yet, it seems like a rather large bug in the latest client to not be able to store values > 1500 characters as a property in a slice

**Comment by okdave** [comment]
Sorry @selfcontained , this slipped under the radar. I'm hoping to look today.

**Comment by okdave** [comment]
It definitely looks like it was caused by 8e17245, although that should not have changed the behaviour for structs at all. Taking a look.

**Comment by okdave** [comment]
OK, the problem is that commit moved the `exclude_from_indexes` property from each element of the `ArrayValue` value to the top-level value itself. Fix forthcoming.

**Comment by gpopovic** [comment]
noindex is still ignored on slices :/

example:

type A struct {
     B []B datastore:"b,noindex"
}

type B struct {
    	Key   string `json:"key" datastore:"key,noindex"`
	Value string `json:"value,omitempty" datastore:"value,noindex"`
}

**Comment by okdave** [comment]
@gpopovic You'll need to be more specific. I can't reproduce an error using the structs you've listed above. What are you trying to do, and how is it failing? A minimal example would be appreciated.

The following passes:
```go
  type B struct {
    Key   string `json:"key" datastore:"key,noindex"`
    Value string `json:"value,omitempty" datastore:"value,noindex"`
  }

  type A struct {
    B []B `datastore:"b,noindex"`
  }

  m := &A{
    B: []B{
      {Key: "a", Value: strings.Repeat("a", 2000)},
    },
  }
// client.Put succeeds for m.
```

I also removed the `noindex` from `B` and from `A` too, and it still worked in both cases (removing from both at the same time failed as expected).

**Comment by gpopovic** [comment]
No matter how much i try these field always end up indexed.

`
package main

import (
	"fmt"

	"golang.org/x/net/context"
	"google.golang.org/cloud/datastore"
)

type A struct {
	B []B `datastore:"b,noindex"`
}

type B struct {
	X string `datastore:"x,noindex"`
	Y string `datastore:"y,noindex"`
}

func main() {
	ctx := context.Background()
	client, err := datastore.NewClient(ctx, "__PROJECT__")
	if err != nil {
		panic(err)
	}

	key := datastore.NewKey(ctx, "__KIND__", "default", 0, nil)

	k, err := client.Put(ctx, key, &A{
		B: []B{
			B{"a", "b"},
			B{"c", "d"},
		},
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(k)
}

`

And it appears to keep being indexed ...
![image](https://cloud.githubusercontent.com/assets/2094147/15679227/5cc01e6e-2751-11e6-9ddf-41350af6205a.png)

**Comment by gpopovic** [comment]
@okdave did you maybe have a time to check this? I can't deploy to a production because of additional cost of those indexes

**Comment by pcostell** [comment]
I wonder if this is just a bug with our UI --

For backwards-compatibility reasons, the array type must always be marked as indexed, however the underlying values aren't necessarily indexed. It's possible (and likely) that the UI only looks at the indexed bit of the top-level property. @gpopovic -- Can you file feedback about this in your UI?

On a separate note, starting July 1st any extra indexes won't cost any extra as the write costs will change to be per entity write (instead of per entity or index write).

**Comment by gpopovic** [comment]
I just hovered with mouse over checkbox and it says this:
Text values and arrays cannot be indexed. 
I thought fields with repeated values could be indexed?

I tried to create an entity with indexed tag field and got the same result.

type A struct {
	Tags []string `datastore:"b"`
}

Tags get marked as ("Text values and arrays cannot be indexed. ")

**Comment by pcostell** [comment]
@gpopovic -- Please file feedback directly in the Cloud Console, it is the best way for the team to see exactly what the error is.

For Array values, the array value field must *always* be indexed, however the individual elements in the array each control their indexing (an array where all the elements are unindexed is technically indexed, however there is no charge for the indexing because there are no entries).
