### ISSUE TITLE
Failed to connect to gcloud emulators.

### ISSUE THREAD

**Issue by yipjustin** [GoogleCloudPlatform/gcloud-golang#257]
Hello,

I am trying to connect to gcloud emulator using `datastore.NewClient` for local development, I am flooded by the following errors.

```
...
2016/05/10 17:31:13 transport: http2Client.notifyError got notified that the client transport was broken read tcp 127.0.0.1:51969->127.0.0.1:8013: read: connection reset by peer.
...
```

I doubled checked that I have set the os.env `DATASTORE_EMULATOR_HOST` and `DATASTORE_PROJECT_ID`. 

But the clients are created successfully when I connect with 1) the actual google cloud datastore and 2) the old standalone gcd emulator (http://storage.googleapis.com/gcd/tools/gcd-grpc-1.0.0.zip).

After some digging, it seems to me that this is the line where the problem arises. https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/datastore/datastore.go#L90

I guess I may have miss something important in creating the client, can anyone give me some pointers?

Here is the code I used to create the client:
```
	nsCtx := datastore.WithNamespace(context.Background(), namespace)

	client, err := datastore.NewClient(nsCtx, projectId,
		cloud.WithTokenSource(conf.TokenSource(nsCtx)))
``` 

Thanks!

**Comment by jba** [comment]
The emulator built into gcloud doesn't support gRPC yet. The workaround, as you've already discovered, is to use the standalone gcd emulator.
