### ISSUE TITLE
Datastore query results replace every 300th result with the previous one.

### ISSUE THREAD

**Issue by lgarron** [GoogleCloudPlatform/gcloud-golang#259]
Reproduce as follows:

`main.go`:

    package main

    import (
    	"fmt"

    	"google.golang.org/cloud/datastore"

    	"golang.org/x/net/context"
    )

    type TestItem struct{}

    func main() {

    	projectID := "hstspreload-mvm"

    	ctx := context.Background()

    	client, err := datastore.NewClient(ctx, projectID)
    	if err != nil {
    		panic(fmt.Sprintf("NewClient: %s", err))
    	}

    	write(ctx, client)
    	read(ctx, client)
    }

    func write(ctx context.Context, client *datastore.Client) {

    	// first and last are inclusive
    	putRange := func(first int, last int) {
    		var keys []*datastore.Key
    		var values []TestItem

    		for i := first; i <= last; i++ {
    			keyName := fmt.Sprintf("key%03d", i)
    			keys = append(keys, datastore.NewKey(ctx, "TestItemDatastoreKind", keyName, 0, nil))
    			values = append(values, TestItem{})
    		}

    		_, err := client.PutMulti(ctx, keys, values)
    		if err != nil {
    			panic(fmt.Sprintf("PutMulti: %s", err))
    		}
    	}

    	// We can only put 500 at a time, so we add our values using multiple puts.
    	// This does not affect the bug, but putting more than 600 entries allows
    	// us to demonstrate it better.
    	putRange(1, 500)
    	putRange(501, 604)
    }

    func read(ctx context.Context, client *datastore.Client) {
    	query := datastore.NewQuery("TestItemDatastoreKind").KeysOnly()
    	keys, err := client.GetAll(ctx, query, nil)
    	if err != nil {
    		panic(fmt.Sprintf("GetAll: %s", err))
    	}

    	for _, key := range keys {
    		fmt.Printf("%s\n", key.Name())
    	}

    }

`go run main.go`:

    key001
    key002
    ...
    key299
    key300
    key001
    key302
    key303
    ...
    key599
    key600
    key301
    key602
    key603
    key604

If you keep adding more keys, you'll find that:

- `key001` appears in place `key301`
- `key301` appears in place `key601`
- `key601` appears in place `key901`
- ...

Therefore, if there are more than 300 results, the first key is duplicate, and the last key of index `≡ 1 (mod 300)` is missing.

**Comment by pcostell** [comment]
I'm not super familiar with the library, but is the issue right here:

https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/datastore/query.go#L660

If we've reached the end of the batch we set the `res` on the iterator, but we don't set the local batch `b` variable. The first time through we'll return the result from the previous batch, but later results then pick up the new batch because we've set `t.res`

**Comment by pcostell** [comment]
Just confirmed that this was this issue. On [#L661][https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/datastore/query.go#L661] there should be `b = r.res.GetBatch()`.

@okdave or @broady, could you handle patching this fix in? I can take it too but am not very familiar with the go development environment.

**Comment by okdave** [comment]
I can take this now. Thanks for the diagnosis @pcostell

**Comment by okdave** [comment]
Pending change at https://code-review.googlesource.com/#/c/4767/

**Comment by lgarron** [comment]
> Pending change at https://code-review.googlesource.com/#/c/4767/

With a test, yay!

The bug in that change is #239. Should it be #259 (this bug), or does it refer to something else?

**Comment by okdave** [comment]
That bug was a bug, sorry. Fixed to reference this one now :)
