### ISSUE TITLE
bigtable/bttest: ReadModifyWriteRow does not update timesstamps

### ISSUE THREAD

**Issue by stxmendez** [GoogleCloudPlatform/gcloud-golang#264]
We were using bttest for some unit tests and realized that it does not update a cell's timestamp when performing a ReadModifyWriteRule_AppendValue or a ReadModifyWriteRule_IncrementAmount operation.

I'll submit a patch to address in case there is interest.

**Comment by garye** [comment]
Thanks, a patch would be great. Instructions are here: https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/CONTRIBUTING.md. If that's a bit more than you wanted to bite off then feel free to attach a patch here and I'll apply it.

**Comment by stxmendez** [comment]
https://code-review.googlesource.com/#/c/4810/

**Comment by garye** [comment]
Merged the patch. Thanks for fixing.
