### ISSUE TITLE
bigquery: Support table options in streaming

### ISSUE THREAD

**Issue by nightlyone** [GoogleCloudPlatform/gcloud-golang#273]
In order to specify:
* templateSuffix (s. https://cloud.google.com/bigquery/streaming-data-into-bigquery#template-tables )
* ignoreUnknownValues
* skipInvalidRows

on streaming, it would be nice to have the ability to pass it on. Currently these missing options are the last blocker preventing usage of https://godoc.org/google.golang.org/cloud/bigquery#Table.NewUploader in our project.

**Comment by jba** [comment]
Probably won't get to this until later this week.

**Comment by nightlyone** [comment]
@jba I started working on it at https://code-review.googlesource.com/4950

It highlights two issues:

1.  We already have IgnoreUnknownValues but for loads, so we cannot easily create a new Option type just for streaming

2. I don't know how to handle unfit options possibly passed to the the problem in 1. and see 3 possibilities
* NewUploader needs to return an error for options not useful to streaming (API change)
* The error needs to be deferred until streaming starts (which I implemented there)
* Uploader.Put() gets all these options and we handle those options, which are usually constant between multiple puts, there.

**Comment by jba** [comment]
When you're ready for review add mcgreevy as well as me.

**Comment by mcgreevy** [comment]
I think an acceptable compromise is to:

* create a new UploadOption type, and
* add a new function, IgnoreUknownUploadValues which returns an UploadOption (it could just return an ignoreUnknownValues, which can implement both interfaces).

This extra function, which effectively duplicates IgnoreUnknownValues, is a bit of a wart, but:
* it retains the ability to find all Options together (same for UploadOptions), and
* it avoids the extra type checking that you mention (and the possible need to introduce an error return value to NewUploader).

**Comment by jba** [comment]
Can we rename IgnoreUnknownValues to IgnoreUnknownLoadValues?

**Comment by nightlyone** [comment]
@jba this renaming would break backward compatibility. I know that, because I use this feature elsewhere 😃

**Comment by jba** [comment]
The package is not guaranteed to be backward-compatible.
https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/bigquery/doc.go#L17
.

Obviously we don't want to break things on a whim, but we do want to evolve
this package (and the others in this repo) to be as excellent as they can
be.

**Comment by okdave** [comment]
I don't think there's harm in leaving `IgnoreUnknownValues` alone: it seems it's the option for the much more common operation.

`UploadIgnoreUnknownOption` also looks good to me. The phrasing is a bit weird, but it makes is very obvious that it's upload-specific.

**Comment by nightlyone** [comment]
ok, thanks for the great feedback guys! I uploaded a second version integration.
@mcgreevy I listed you as a reviewer. Please add any person, who should take a look. 

Looking forward to the next round :smile:

**Comment by nightlyone** [comment]
ok @jba and @mcgreevy https://code-review.googlesource.com/#/c/4950 is ready to be merged now as all issues raised have been addressed. 

Then I can finally use the uploader in our products at work :tada:
