### ISSUE TITLE
bigtable: Client Close should return the error

### ISSUE THREAD

**Issue by ilonajulczuk** [GoogleCloudPlatform/gcloud-golang#276]
Client, AdminClient and ClusterAdminClient don't return anything from their Close method, e.g. here: https://godoc.org/google.golang.org/cloud/bigtable#Client.Close

however they close the grpc ClientConn under the hood:

```
c.conn.Close()
```

and the error returned by `grpc.ClientConn` Close method is quietly ignored. 
This behavior is bad, because if the error actually happens, users of the library don't have any way to learn about it and react.

**Comment by garye** [comment]
Fixed
