### ISSUE TITLE
transport/grpc: add support for GAE standard

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/gcloud-golang#277]
We should automatically use the `appengine/socket.Dialer`.

**Comment by bradfitz** [comment]
Can you elaborate?

**Comment by broady** [comment]
To use any gRPC backed Cloud package, the user must do something like this:

```
	dialOpt := cloud.WithGRPCDialOption(grpc.WithDialer(func(addr string, timeout time.Duration) (net.Conn, error) {
		return socket.DialTimeout(ctx, "tcp", addr, timeout)
	}))
	client, err := datastore.NewClient(ctx, projectID, dialOpt)
```

We should do this for them.

**Comment by dsymonds** [comment]
How are you going to thread the `ctx` into there?

**Comment by broady** [comment]
We should take the `ctx` from the `NewClient` function.

On GAE standard, users are creating a new `Client` for every incoming request.

**Comment by dsymonds** [comment]
That approach is probably fine. I thought you were suggesting doing this in the grpc-go package

**Comment by broady** [comment]
Oh, no. Unfortunately gRPC's `Dial` doesn't take a context as a parameter, so that's not possible.

**Comment by broady** [comment]
https://code-review.googlesource.com/#/c/5050/
