### ISSUE TITLE
cannot use "google.golang.org/cloud/bigquery".BatchPriority (type string)

### ISSUE THREAD

**Issue by albertog** [GoogleCloudPlatform/gcloud-golang#279]
When build my cod
job, err := client.Copy(e.ctx, dest, query, bigquery.WriteTruncate, bigquery.BatchPriority)

error.

./app.go:57: cannot use "google.golang.org/cloud/bigquery".BatchPriority (type string) as type "google.golang.org/cloud/bigquery".Option in argument to client.Copy:
	string does not implement "google.golang.org/cloud/bigquery".Option (missing "google.golang.org/cloud/bigquery".implementsOption method)

only bigquery.WriteTruncate works fine

**Comment by jba** [comment]
Try `bigquery.JobPriority(bigquery.BatchPriority)`

So the full line would be
```
 job, err := client.Copy(e.ctx, dest, query, bigquery.WriteTruncate, bigquery.JobPriority(bigquery.BatchPriority))
```

**Comment by albertog** [comment]
wow perfect work propertly.  thanks
