### ISSUE TITLE
bigquery add allowlargeresult and flatten

### ISSUE THREAD

**Issue by albertog** [GoogleCloudPlatform/gcloud-golang#282]
this two options is very useful and is not implemented.

many thanks

... capture from bigquery code
// TODO(mcgreevy): support large results.
// TODO(mcgreevy): support non-flattened results.

func (c *Client) query(ctx context.Context, dst *Table, src *Query, options []Option) (*Job, error) {
	job, options := initJobProto(c.projectID, options)
	payload := &bq.JobConfigurationQuery{}

	dst.customizeQueryDst(payload, c.projectID)
	src.customizeQuerySrc(payload, c.projectID)

	for _, opt := range options {
		o, ok := opt.(queryOption)

**Comment by jba** [comment]
Thanks, Alberto. We'll work on it.

**Comment by nightlyone** [comment]
@albertog AFAICS it is already implemented in https://github.com/GoogleCloudPlatform/gcloud-golang/commit/8403221f9be14d46a3768bf2bd217bab1de3c520

see https://godoc.org/google.golang.org/cloud/bigquery#AllowLargeResults

Maybe you need to update your version?

**Comment by nightlyone** [comment]
@jba IMHO a duplicate of https://github.com/GoogleCloudPlatform/gcloud-golang/issues/207

**Comment by jba** [comment]
Thanks, @nightlyone. 

@albertog, can you verify by updating your client and trying again? Let us know so we can close this.

**Comment by albertog** [comment]
I have update and now we have allowLargeResults and DisableFlatten but not all have been fixed. I try to explain.

We have this sql statement to copy to another table

----
SELECT
JSON_EXTRACT(json, '$.producto_tags') producto_tags, // NOTE  IT IS A ARRAY
FROM
  [qdata_raw.InputDataAll]
WHERE
  msg = 'Productos'
---

The issue is now we can copy te field to dest table but it is copy as string field ["PCMSL","PCMSG"] and it should be a repeated  of strings. If you perform same action via web ui  work propertly.

thanks

**Comment by jba** [comment]
Thanks, will look into it.

**Comment by jba** [comment]
I think this is working as intended. The only strange part is the web UI behavior.

The [documentation for JSON_EXTRACT](https://cloud.google.com/bigquery/query-reference#jsonfunctions) says that it returns the value "in JSON string format". That means as a string. So the copy is doing the right thing.

To check this, I used `bq` to make a simple table with a similar structure to yours:

```shell
> bq show ds1.products
Table proj:ds1.products

   Last modified              Schema             Total Rows   Total Bytes   Expiration  
 ----------------- ---------------------------- ------------ ------------- ------------ 
  01 Jul 18:09:38   |- ID: integer (required)    0            0                         
                    |- msg: string (required)                                           
                    |- json: string (required)
```

Then I wrote a query like yours and put the results in a new table:

```shell
> bq query  --destination_table ds1.ptags  '
   select json_extract(json, "$.tags") tags from ds1.products
   where msg = "m1"'
+------------------+
|       tags       |
+------------------+
| ["t1"]           |
| ["t1","t2","t3"] |
| []               |
+------------------+
```

The resulting table has one column of type string:
```shell
> bq show ds1.ptags
Table proj:ds1.ptags

   Last modified        Schema        Total Rows   Total Bytes   Expiration  
 ----------------- ----------------- ------------ ------------- ------------ 
  01 Jul 18:17:10   |- tags: string   3            30                       
```

**Comment by albertog** [comment]
I have re-done the exercise and it is correct so thanks for your support. I will close te issue.
