### ISSUE TITLE
SignedURL should not require a private key when running in app engine

### ISSUE THREAD

**Issue by BrandonY** [GoogleCloudPlatform/gcloud-golang#286]
The storage module provides a "SignedUrl" method which takes in some parameters, including a private key, generates a URL, and then signs that URL with the input private key.

App Engine provides an "appengine.SignBytes" method which signs arbitrary bytes with the key of the running application. If the library is running within app engine, it should be able to use this function to sign the key without requiring a key as input.

**Comment by okdave** [comment]
https://cloud.google.com/storage/docs/access-control/signed-urls#signing-gae for reference.

**Comment by LAndreas** [comment]
@BrandonY see: https://code-review.googlesource.com/5280 `storage: add SignBytes field to SignedURLOptions` :)

**Comment by wmark** [comment]
Module `appengine` is marked as *deprecated*, making this relevant again.
