### ISSUE TITLE
`gcloud preview app` will go away

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/gcloud-golang#289]
gcloud-golang/examples/bigtable/bigtable-hello/README.md

has 2 instances of `gcloud preview app`.

For `gcloud preview app run`, please consider running the application server locally.
For `gcloud preview app deploy`, just use `gcloud app deploy`.

**Comment by rakyll** [comment]
> For gcloud preview app run, please consider running the application server locally.

Is there an equivalent gcloud command for that?

**Comment by adamtanner** [comment]
> Is there an equivalent gcloud command for that?

It was removed in favor of running dev_appserver.py directly.

**Comment by rakyll** [comment]
Closed via ac4f44b01aac6f98356767d29ac0de7cc20dcfaf.
