### ISSUE TITLE
pubsub: Pull msgs call msgs[0].done(true) cause panic

### ISSUE THREAD

**Issue by lbeeon** [GoogleCloudPlatform/gcloud-golang#291]
*Message could get the ackid, and data, but could not call the method "done".
Error message:`panic: runtime error: invalid memory address or nil pointer dereference`
Works fine with pubsub.Ack(). Is it a bug or wrong way to use?

**Comment by mcgreevy** [comment]
I'm not sure exactly how you are using the library, but it sounds like you care attempting to call Done on a message that was returned by the deprecated Pull method.  Per the documentation, Done may only be called on a Message which was returned by an Iterator.

Note: pubsub.Pull and pubsub.Ack are deprecated, so you should migrate to using Subscription.Pull to get an Iterator, and then call Done on the Messages that it returns.
