### ISSUE TITLE
pubsub: delete the flat functions

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/gcloud-golang#297]
With the high level structs like Topic and Subscription, we can deprecate the old flat functions listed below to keep things orthogonal.  If there are any concerns or additional feedback, please comment.

```
func Ack(ctx context.Context, sub string, id ...string) error
func CreateSub(ctx context.Context, name string, topic string, deadline time.Duration, endpoint string) error
func CreateTopic(ctx context.Context, name string) error
func DeleteSub(ctx context.Context, name string) error
func DeleteTopic(ctx context.Context, name string) error
func ModifyAckDeadline(ctx context.Context, sub string, id string, deadline time.Duration) error
func ModifyPushEndpoint(ctx context.Context, sub, endpoint string) error
func Publish(ctx context.Context, topic string, msgs ...*Message) ([]string, error)
func Pull(ctx context.Context, sub string, n int) ([]*Message, error)
func PullWait(ctx context.Context, sub string, n int) ([]*Message, error)
func SubExists(ctx context.Context, name string) (bool, error)
func TopicExists(ctx context.Context, name string) (bool, error)
``` 

/cc @mcgreevy @broady

**Comment by broady** [comment]
They've been marked as deprecated since Feb 3, we should remove them soon.

https://code-review.googlesource.com/#/c/4113/
9d72489da91819fc89702995922b6fada8b85c00

**Comment by okdave** [comment]
That's right, we've already moved them into their own file (named legacy) and they'll be removed in the near future (there are couple of backwards-incompatible changes in the pipeline and we want to do them at once with some notification on the announce group).
