### ISSUE TITLE
bigtable: implement zero-copy row value reading

### ISSUE THREAD

**Issue by rameshdharan** [GoogleCloudPlatform/gcloud-golang#302]
Forgive me if I'm missing something here since I'm mostly a golang newbie, but AFAICT there isn't a way to do zero-copy processing of results from a ReadRows operation, since the callback passed to ReadRows owns the Row argument and it's passed by value. 

A version of ReadRows that allocated the Row result using new and passed it by pointer to the callback would address this issue. A brief peek at the internal implementation suggests that perhaps we could also eliminate another internal copy there as well given the way cr.curVal is handled.

**Comment by jba** [comment]
A Row is a map, and maps are basically pointers under the hood. So there's no copying.

**Comment by jba** [comment]
Just noticed your comment on cr.curVal. There is an allocation there, but I don't know if it can be eliminated. @garye knows that code best.

**Comment by garye** [comment]
@rameshdharan Are you talking about:
`cr.curVal = make([]byte, 0, cc.ValueSize)`? 
That's only necessary if the cell data is split across multiple chunks and we need to pre-allocate space for the entire cell. This only happens with very large rows. The normal path doesn't do an allocation.

**Comment by rameshdharan** [comment]
Thanks @jba, point taken re: Row being a map, didn't realize that and that makes sense to me. 

Discussed with @garye, but to recap here I was concerned that the assignment of cr.curVal into the ReadItem in finishCell would incur a copy, but actually since that's a slice type, there's no copy incurred there either. 

So, I think it's fine to close this out now (invalid).
