### ISSUE TITLE
storage: handle content-type properly

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/gcloud-golang#306]
> Dear Google Cloud Storage JSON API customer,
> 
> Important: Following up from our recent emails, a change to improve Google Cloud Storage's JSON API request validation is currently being rolled out. It will cause some of the types of object uploads that you have made recently to be rejected as invalid requests. If you have already made code changes to avoid this problem, then thank you; you can stop reading now. Otherwise, you will likely start experiencing increasing service errors as the change is rolled out.
> 
> Google Cloud Storage is making a bug-fix change to ensure that objects are always given the Content-Type intended by the uploader. You are being contacted as a project-owner of a project whose buckets have received upload requests in the last two weeks that will, under the new validation, be rejected because the Content-Type as specified by the media does not match the Content-Type as specified by the metadata. The following buckets, listed by project, have been identified as having received such upload requests:
> 
> <snip>
> 
> If you upload content using:
> 
> uploadType=media, there is nothing to address in that code path, as this upload type is not impacted by the change.
> uploadType=multipart, then if you specify a contentType in the JSON body of the first part, and you specify a Content-Type header of the second part, and they do not match, the request will be rejected.
> uploadType=resumable, then if you specify a contentType in the JSON body of the request to initiate the resumable upload session, and you specify a X-Upload-Content-Type header on that same request, and they do not match, the request will be rejected.
> From our analysis, of the tiny fraction of customers who are affected by this change, all are using https://github.com/google/google-api-go-client. The Go client defaults to trying to auto-determine the Content-Type of the Media provided for upload and often conflicts with any custom contentType that was provided in the object's metadata. This behavior can be suppressed with the MediaOptions.ContentType("") as described here, with code that looks like:
> 
> result, err := svc.Objects.Insert("BUCKET", &storage.Object{Name: "OBJECT", ContentType:"example/foo"}).Media(file, googleapi.ContentType(""))
> 
> This capacity was added with this commit, so update your Go client, and update your code. If you have any questions or concerns, please do not hesitate to contact us.
>

**Comment by okdave** [comment]
This is handled correctly in this API (see #221: we don't allow the header and the JSON field to be set to different content types).  We should re-open google/google-api-go-client#134 to make sure that the Apiary client similarly stops users from inadvertently shooting themselves in the foot.
