### ISSUE TITLE
internal/bundler is flaky

### ISSUE THREAD

**Issue by okdave** [GoogleCloudPlatform/gcloud-golang#308]
For me, it's failing ~12% of the time:
```
$ go test -c cloud.google.com/go/internal/bundler
$ for i in {1..25}; do ./bundler.test; done
```

**Comment by jba** [comment]
Could not replicate on my workstation, but did on my laptop. The joys of timing.

**Comment by okdave** [comment]
This seems to still be a problem on travis:
https://travis-ci.org/GoogleCloudPlatform/gcloud-golang/jobs/150853065

Is there a way we can make it deterministic (fake the time for tests, or similar)?

**Comment by jba** [comment]
I don't see an easy way to fake time. Instead I relaxed the test a bit.
