### ISSUE TITLE
trace: use consistent naming for Span constructors

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/gcloud-golang#313]
There are two naming styles for the span constructors:

* (*Client).SpanFromRequest
* FromContext

Drop Span from SpanFromRequest or add Span to FromContext.

/cc @jba @okdave

**Comment by jba** [comment]
We usually use NewContext and FromContext to add and extract things from Contexts. So FromContext seems OK. Usually we manage to align the package name with what is being returned, e.g. golang.org/x/net/trace.FromContext returns a Trace. It's unfortunate that it returns something different here. Maybe that's what we should look at: why does the x/net/trace package uses Traces where this one uses Spans?

SpanFromRequest seems like a reasonable name for what it does. I don't think we should drop "Span" from that; then it would suggest something different.

**Comment by rakyll** [comment]
Span is introduced by the Trace API and it might be a valuable to keep the same terminology so users can match the concepts while they are reading the generic API docs.

I guess the better naming for FromContext should be SpanFromContext indicating that it is a Span accessor. There is one nit that it is a bit longer name though.

**Comment by derekperkins** [comment]
Working through the trace library with @broady, we came up with a simpler API to interact with the library - see #298

**Comment by okdave** [comment]
Closing this in favour of #298.
