### ISSUE TITLE
godoc examples are not being compiled

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/gcloud-golang#320]
See https://github.com/golang/go/issues/16773 for context.

Something in the tooling has changed and they are omitting to compile the examples if there is no output section. None of our examples are being built during go test.

**Comment by okdave** [comment]
IIUC, this is only going to affect 1.7? As long as it's fixed in 1.8 (or even better, 1.7.x) we should be fine since at least the examples are still being checked for correctness in 1.6.

**Comment by rakyll** [comment]
It is currently a non-issue for me, closed the original bug as well. https://github.com/golang/go/issues/16773#issuecomment-241473447

Please update the bug if you experience an unexpected behavior.
