### ISSUE TITLE
bigtable: using PrefixRange and LimitRows with emulator doesn't seem to work

### ISSUE THREAD

**Issue by jmhodges** [GoogleCloudPlatform/gcloud-golang#322]
Hey, new to the bigtable API, so I'm sure I could just be getting this code wrong. (It could also possibly be a bug in the emulator, but I'm starting here).

I have this test that's running against the beta bigtable emulator. It uses PrefixRange and LimitRows and my expectation was that it would give me only one of the Rows I wrote, instead of the 2 total that were inserted.

I'm sure I've just got something wrong, but not clear what it is!

    package bt
    
    import (
	    "context"
	    "testing"
	    "time"
    
	    "cloud.google.com/go/bigtable"
    )
    
    func TestGoldenPath(t *testing.T) {
	    ctx := context.Background()
	    admin, err := bigtable.NewAdminClient(ctx, "", "")
	    if err != nil {
		    t.Fatal(err)
	    }
	    f := func() {
		    err = admin.DeleteTable(ctx, "client_histories")
		    if err != nil {
			    t.Logf("if this is a 'no such table' error, don't worry about it: %s", err)
		    }
	    }
	    f()
	    defer f()
	    err = admin.CreateTable(ctx, "client_histories")
	    if err != nil {
		    t.Fatal(err)
	    }
	    err = admin.CreateColumnFamily(ctx, "client_histories", "msgs")
	    if err != nil {
		    t.Fatal(err)
	    }
    
	    client, err := bigtable.NewClient(ctx, "", "")
	    if err != nil {
		    t.Fatal(err)
	    }
    
	    tbl := client.Open("client_histories")

	    m1 := bigtable.NewMutation()
	    m1.Set("msgs", "M0001", bigtable.ServerTime, []byte("msg1"))
	    err = tbl.Apply(context.Background(), "foobar:0001.0000", m1)
	    if err != nil {
		    t.Fatal(err)
	    }

	    m2 := bigtable.NewMutation()
	    m2.Set("msgs", "M0001", bigtable.ServerTime, []byte("msg2"))
	    err = tbl.Apply(context.Background(), "foobar:0001.0000", m2)
	    if err != nil {
		    t.Fatal(err)
	    }

	    m3 := bigtable.NewMutation()
	    m3.Set("msgs", "M9999.9998", bigtable.ServerTime, []byte("msg2"))
	    err = tbl.Apply(context.Background(), "foobar:0999.9998", m3)
	    if err != nil {
		    t.Fatal(err)
	    }
    
	    rs := []bigtable.Row{}
	    pr := bigtable.PrefixRange("foobar:")
	    tbl.ReadRows(ctx,
		    pr,
		    func(r bigtable.Row) bool {
			    rs = append(rs, r)
			    return true
		    },
		    bigtable.LimitRows(1),
	    )
	    if len(rs) != 1 {
		    t.Fatalf("row count: want %d, got %d", 1, len(rs))
	    }
    }

**Comment by jmhodges** [comment]
(Cleaned up the `time.Sleep`s I had in there while debugging a different deal)

**Comment by jmhodges** [comment]
Hm, this also occurs when using `bttest.Server` so it's probably either my misunderstanding of the API or a client bug.

I'm really not sure which and would love to be educated on this one.

**Comment by jmhodges** [comment]
So, I updated my code from e977e3911f5ba211c715d40c30fc81abfa9400ae to 242ed68074e53cbb6f78a90c28d9a48bfa2d1093 and now the `bttest.Server` version works correctly, but the emulator still does not.

I think the emulator needs a patch equivalent to https://github.com/GoogleCloudPlatform/gcloud-golang/commit/e9eae4f583465473e798f6fea7f46beb41ffff85

Not sure where to make a ticket for the emulator. Will poke around but guidance welcome.

**Comment by garye** [comment]
The emulator is just a compiled version of bttest (https://github.com/GoogleCloudPlatform/gcloud-golang/tree/master/bigtable/cmd/emulator). It will take a week or so to get this fix released with gcloud but in the meantime hopefully you can make progress running the emulator directly. 

Since bttest == emulator feel free to make any tickets for it here.

**Comment by jmhodges** [comment]
Ah! Shoot! I just made a ticket for this. https://code.google.com/p/google-cloud-sdk/issues/detail?id=1073

Feel free to close that one. I'll close this one now.

Thank you very much!
