### ISSUE TITLE
datastore: extracting __key__ from a projection?

### ISSUE THREAD

**Issue by jmhodges** [GoogleCloudPlatform/gcloud-golang#328]
I'd like to shove the keys of the rows returned by a Project query directly into the structs that I'm calling `GetAll` with (and, by doing so, avoid having to iterate over the keys GetAll returns). My attempts so far have pulled up blanks.

Maybe this isn't a thing? I've tested against the emulator (specifically, `--no-legacy`) but haven't shipped to prod, yet, to see if its just an emulator bug. Digging into the code, it seems like its being dropped in the emulator but maybe I've not asked it the right parameter.

Here was an early attempt I made:

    type TeamToken struct {
        ID     string `datastore:"__key__"`
        Token  string `datastore:"token"`
    }
    ...
    q := datastore.NewQuery('Team').
        Project("token")
    teamToks := []TeamToken{}
    _, err := ttr.ds.GetAll(ctx, q, &teamToks)
    if err != nil {
        return nil, err
    }

I also tried including `__key__`   explicitly in the projection:

    q := datastore.NewQuery(teamTokenEntity).
        Project("__key__", "token")

Oh, and I have also tried both of those but with `ID *datastore.Key` as the field in TeamToken.

Both of these returned `TeamToken`s that had no `ID` field set while the `Token` field was.

**Comment by jmhodges** [comment]
Oh, maybe the deal is that, since I'm asking for the string name I set on the team token, there's some other parameter (`__name__`?) that I need to query for.

Man, the stuff you come up with after waiting and waiting and waiting to make the ticket and then think up immediately after you post.

**Comment by jmhodges** [comment]
Hm, haven't been able to find a magic parameter that means "give me the string key name" in my googling and code diving.

**Comment by okdave** [comment]
I would be surprised if something like that would work at all. The `__key__` property isn't a real property. It sometimes is supported for things like query filters, but the actual [underlying protocol buffer representation](https://godoc.org/google.golang.org/genproto/googleapis/datastore/v1#Entity) has the key very clearly to the side of the property map.

The Go code for datastore certainly won't try to pull invent a `__key__` or `__name__` property for you. Unless the [datastore documentation](https://cloud.google.com/datastore/docs/concepts/queries#projection_queries) explicitly calls out these special names as available for projection, I wouldn't rely on the server doing so either.

So, my 2c: loop over the keys after your call to `GetAll`. It's using documented APIs so you know it will work, and it's cheap to do.
