### ISSUE TITLE
datastore: insert example has busted Get and datastore.ErrNoSuchEntity check

### ISSUE THREAD

**Issue by jmhodges** [GoogleCloudPlatform/gcloud-golang#330]
The Go version of the [docs for inserting](https://cloud.google.com/datastore/docs/concepts/entities)  (in contrast to upserting) point to [this code sample](https://github.com/GoogleCloudPlatform/gcloud-golang/blob/667e96c2105de5035a927cafb03a7c09ec982d6b/datastore/examples_test.go#L173-L176) which has a bug.

    if err := tx.Get(taskKey, nil); err != datastore.ErrNoSuchEntity {
            log.Fatalf("tx.Get returned err %v, want ErrNoSuchEntity", err)
    }

`ErrNoSuchEntity` will never be returned because calling `tx.Get` with a nil message is always returning `ErrInvalidEntityType`.

The error occurs [inside `newStructPLS`](https://github.com/GoogleCloudPlatform/gcloud-golang/blob/667e96c2105de5035a927cafb03a7c09ec982d6b/datastore/prop.go#L266). The call chain is `Transaction.Get` to `Client.get` to `loadEntity` to `LoadStruct` to `newStructPLS`.

I'm not sure where along in this change we should allow the nil. `Client.get` seems the most reasonable place to check for it? Maybe only allowed in the case of a single key query coming straight from a `Get` and not `MultiGet` call?

Or maybe there should be a `Client.GetKey`?

**Comment by jmhodges** [comment]
The workaround, of course, is to use an actual pointer to a struct for this and just ignore whatever gets put inside it.

**Comment by rakyll** [comment]
The example seems to be misleading, we need to pass the task's pointer.

**Comment by okdave** [comment]
Yes, we should fix this.

The example is obviously wrong, but I feel like we should accept `nil` for `Get` (in the same way that we do already for the query iterator's `Next` method) for cases like this when all you want is an existence check.

**Comment by rakyll** [comment]
If we should support nil on Get, maybe keeping the example as-it-is is a better idea. We are just checking the existence and die if exists.

**Comment by okdave** [comment]
I'd vote to fix the example now, and support `Get(key, nil)` later (since it's more of a feature request anyway).

**Comment by jmhodges** [comment]
Thanks!
