### ISSUE TITLE
Emit header for gRPC messages

### ISSUE THREAD

**Issue by pcostell** [GoogleCloudPlatform/gcloud-golang#333]
gRPC connections currently don't have enough information in the request for us to do efficient traffic management/routing. 

Will you add a header that allows for us to optimize for this on the server? The header format is:

```
name: google-cloud-resource-prefix
value: projects/my-project-id
```

In general, the prefix would be the same as the JSON-over-http URL up to any custom method. For example, a Cloud Datastore commit message over JSON would hit the url `projects/my-project-id:commit`.

Here is an example usage in the cloud-bigtable-client: https://github.com/GoogleCloudPlatform/cloud-bigtable-client/pull/915/files#diff-1078787e69bc1d7c5bb8507f0a87a143R83

**Comment by garye** [comment]
The bigtable client is already doing this as of:
https://github.com/GoogleCloudPlatform/gcloud-golang/commit/4f1a5ca1c906ba5ff5ff9fba3bee49d526a8d03f

**Comment by pcostell** [comment]
Awesome! Can we add it for Cloud Datastore too?

**Comment by garye** [comment]
@jba or @okdave can probably weigh in on that.

**Comment by jba** [comment]
I don't see any problem with it. 

I'd suggest @adams-sarah for Datastore. Do you care about the other clients?

**Comment by pcostell** [comment]
I care mostly about Datastore (but am biased). I think this will be generally useful for all the services.

**Comment by adams-sarah** [comment]
SGTM. @shantuo, do you want to take this one?
If not I'm happy to implement.
