### ISSUE TITLE
Need to ensure we use lower-case gRPC header keys

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/gcloud-golang#334]
**This might be a no-op, but please double check. Filing this issue just in case.**

We need to ensure that all headers used for gRPC are written in lower-case. Please review this [Pull Request](https://github.com/GoogleCloudPlatform/gcloud-python/pull/2212) for reference of what needs to be updated.

Again, perhaps this doesn't apply to your language. Feel free to comment and close the issue (after you double checking).

**Comment by broady** [comment]
Yup, handled by `net/http`.
