### ISSUE TITLE
datastore: GetAll is terminated by RST_STREAM

### ISSUE THREAD

**Issue by andrewladd** [GoogleCloudPlatform/gcloud-golang#337]
Good afternoon, 

When trying to use datastore.Client.GetAll in production (ie communicating with Google Datastore rather than an emulator), I receive this message: 

`rpc error: code = 13 desc = stream terminated by RST_STREAM with error code: 2`

The context in which I'm using the function is simple: return a list of entities that are stored under a known parent, and sort them by an integer. Here's my code: 

```
History struct {
    Id string
}

Entry struct {
	Position    float64
	State       string
	PatchTime   float64
}

func dbGetChatHistory(id string, ctx context.Context, client *datastore.Client) ([]*Entry, AppErr) {

	historyKey := datastore.NewKey(ctx, "History", id, 0, nil)

	entries := []*Entry{}

	q := datastore.NewQuery("Entry").
		Ancestor(historyKey).
		Order("-PatchTime")

	_, err := client.GetAll(ctx, q, &entries)
	if err != nil {
		log.Panicf("Error has occured while getting history: %s", err)
		return []*Entry{}, AppErr {
			Code: 500,
			Msg: "Error has occured while getting history",
		}
	}

	return entries, AppErr{}
}
```
I've tried running this query within a transaction (which I don't think is necessary, as this is an ancestor query), as well as setting up the `entries` array a few different ways (ie using `make` to allocate space, using `var entires []*Entry', etc). 

The weirdest part about this whole thing is that it works with the provided emulator; while on my machine, I'm able to use GetAll freely. However, while running this on Google Container Engine, communicating with Datastore, it fails. 

What could I be missing? Is this a problem with DataStore?

**Comment by bradfitz** [comment]
In HTTP/2, error code 2 is an INTERNAL_ERROR (http://httpwg.org/specs/rfc7540.html#rfc.section.7). It'd be nice if we got more details, though.

**Comment by andrewladd** [comment]
There isn't much else to give; that function is directly hooked up an endpoint in my API, and when it's called, it breaks. After some prying, I was able to get it to print a stack trace: 

```
[PANIC RECOVER] Error has occured while getting history: rpc error: code = 13 desc = stream terminated by RST_STREAM with error code: 2 goroutine 188 [running]:
github.com/labstack/echo/middleware.RecoverWithConfig.func1.1.1(0xa00380, 0x1000, 0xf440000, 0xc54be0, 0xc4201ca380)
	/go/src/github.com/labstack/echo/middleware/recover.go:75 +0x147
panic(0x8e72a0, 0xc42044d730)
	/usr/local/go/src/runtime/panic.go:458 +0x243
log.Panicf(0x9cc9eb, 0x2b, 0xc4204b7728, 0x1, 0x1)
	/usr/local/go/src/log/log.go:327 +0xe3
main.dbGetChatHistory(0xc4203b34ce, 0x24, 0x7f5fb6b53068, 0xc420141ce0, 0xc420179180, 0x44d724, 0xc42043a1d7, 0x9b3f7c, 0x1, 0x18, ...)
	/go/src/app/meshdata.go:204 +0x2fa
main.getChatHistory(0xc54be0, 0xc4201ca380, 0x7f5fb6b53068, 0xc420141ce0, 0xc420179180, 0xc42043a1c0, 0xc4200378b0, 0x0, 0x0, 0xc420037868, ...)
	/go/src/app/meshcontroller.go:160 +0x99
main.api.func4(0xc54be0, 0xc4201ca380, 0xc4200378d0, 0x5461f3)
	/go/src/app/api.go:59 +0x68
github.com/labstack/echo.(*Echo).add.func1(0xc54be0, 0xc4201ca380, 0xa00380, 0x1000)
	/go/src/github.com/labstack/echo/echo.go:474 +0x96
github.com/labstack/echo/middleware.RecoverWithConfig.func1.1(0xc54be0, 0xc4201ca380, 0x0, 0x0)
	/go/src/github.com/labstack/echo/middleware/recover.go:82 +0x124
github.com/labstack/echo/middleware.LoggerWithConfig.func2.1(0xc54be0, 0xc4201ca380, 0x0, 0x0)
	/go/src/github.com/labstack/echo/middleware/logger.go:107 +0x194
main.auth.func1(0xc54be0, 0xc4201ca380, 0x3, 0xc4203b34c0)
	/go/src/app/server.go:92 +0x54
github.com/labstack/echo.(*Echo).ServeHTTP.func1(0xc54be0, 0xc4201ca380, 0x0, 0x28)
	/go/src/github.com/labstack/echo/echo.go:555 +0x154
github.com/labstack/echo/middleware.RemoveTrailingSlashWithConfig.func1.1(0xc54be0, 0xc4201ca380, 0xc42000c418, 0x7f5fb6b63340)
	/go/src/github.com/labstack/echo/middleware/slash.go:116 +0x27b
github.com/labstack/echo.(*Echo).ServeHTTP(0xc4201c00a0, 0xc514a0, 0xc4203b2740, 0xc4f980, 0xc420440000)
	/go/src/github.com/labstack/echo/echo.go:564 +0x1e5
github.com/labstack/echo/engine/fasthttp.(*Server).ServeHTTP(0xc420055e80, 0xc420496480)
	/go/src/github.com/labstack/echo/engine/fasthttp/server.go:143 +0x29a
github.com/labstack/echo/engine/fasthttp.(*Server).ServeHTTP-fm(0xc420496480)
	/go/src/github.com/labstack/echo/engine/fasthttp/server.go:89 +0x34
github.com/valyala/fasthttp.(*Server).serveConn(0xc420079180, 0xc4f6e0, 0xc420026438, 0x8e0201, 0xc420280101)
	/go/src/github.com/valyala/fasthttp/server.go:1528 +0x573
github.com/valyala/fasthttp.(*Server).(github.com/valyala/fasthttp.serveConn)-fm(0xc4f6e0, 0xc420026438, 0xc42013ff58, 0xc42044f601)
	/go/src/github.com/valyala/fasthttp/server.go:1245 +0x3e
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc420055f80, 0xc4201d4660)
	/go/src/github.com/valyala/fasthttp/workerpool.go:210 +0xde
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc420055f80, 0xc4201d4660, 0x8ca680, 0xc4201d4660)
	/go/src/github.com/valyala/fasthttp/workerpool.go:182 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
	/go/src/github.com/valyala/fasthttp/workerpool.go:184 +0x111

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7f5fb6b53fe8, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420185cd0, 0x72, 0xc420049880, 0xc42000c1a8)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420185cd0, 0xc476e0, 0xc42000c1a8)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc420185c70, 0x0, 0xc457a0, 0xc420445700)
	/usr/local/go/src/net/fd_unix.go:419 +0x238
net.(*TCPListener).accept(0xc420026698, 0x436f5e, 0xa01318, 0xc420028800)
	/usr/local/go/src/net/tcpsock_posix.go:132 +0x2e
net.(*TCPListener).Accept(0xc420026698, 0x9, 0x43da16, 0x3, 0x72a941)
	/usr/local/go/src/net/tcpsock.go:222 +0x49
github.com/valyala/fasthttp.acceptConn(0xc420079180, 0xc4c2e0, 0xc420026698, 0xc420049b30, 0xc4f6e0, 0xc420026438, 0x0, 0x0)
	/go/src/github.com/valyala/fasthttp/server.go:1284 +0x49
github.com/valyala/fasthttp.(*Server).Serve(0xc420079180, 0xc4c2e0, 0xc420026698, 0x5, 0xc4c2e0)
	/go/src/github.com/valyala/fasthttp/server.go:1253 +0x1e3
github.com/valyala/fasthttp.(*Server).ListenAndServe(0xc420079180, 0xc42019ed88, 0x5, 0xc420055

```
Any ideas?

**Comment by andrewladd** [comment]
I guess I could outline what router/middleware I'm using. 

Echo framework, with the fasthttp backend: https://github.com/labstack/echo
Middleware: [Logger](https://godoc.org/github.com/labstack/echo/middleware#Logger),  [Recover](https://godoc.org/github.com/labstack/echo/middleware#Recover),  [RemoveTrailingSlash](https://godoc.org/github.com/labstack/echo/middleware#RemoveTrailingSlash). 

The endpoint I'm hitting where it fails is: 
```
endpoints.GET("/:id/history", func(req echo.Context) error {
		res, err := getChatHistory(req, ctx, client)
		if err.Code != 0 {
			return &echo.HTTPError{
				Code:  err.Code,
				Message: err.Msg,
			}
		}
		return req.JSON(http.StatusOK, res)
	})
```

`getChatHistory` calls dbGetChatHistory after parsing the `req` object.

**Comment by andrewladd** [comment]
To add, I receive this error periodically: 

`http2Client.notifyError got notified that the client transport was broken EOF.`

**Comment by bradfitz** [comment]
Sorry, I meant more details from Google's server.

**Comment by andrewladd** [comment]
I'm not sure what info I could provide. Am I able to see datastore's logs? Do you mean how my personal server is configured?

**Comment by garye** [comment]
Are you seeing `http2Client.notifyError got notified that the client transport was broken EOF.` every 4 minutes? I believe that's unnecessary gRPC logging that happens on an idle connection and unrelated to `RST_STREAM`.

**Comment by andrewladd** [comment]
@garye Yeah, I am. I just figured I'd mention as it looks related, but I guess not! Thanks for the info.

**Comment by okdave** [comment]
@andrewladd, are you able to share how you're setting up the `*datastore.Client`?

Is there any other difference between environments when you try emulator vs. prod datastore?

**Comment by andrewladd** [comment]
@okdave Yep! Here's where I set up the context and client objects, where `env` is gathered as an environment variable and `projId` is just a placeholder: 

```
ctx := context.Background()
ctx = datastore.WithNamespace(ctx, env)
client, err := datastore.NewClient(ctx, projId)
```
These get passed down into my router, and in turn into the functions that communicate with the database.

The only difference should be the `env` variable; everything else is consistent.

**Comment by okdave** [comment]
This is very confusing – I can't see what's happening at all. @pcostell @zombiezen, do you have any idea how we might be able to find internal logs to match?

@andrewladd how many entities are you expecting to match the query? If you artificially limit the number do you see the HTTP error? Does it happen reliably? (Sorry for the 20 questions, still trying to get my head around this)

**Comment by andrewladd** [comment]
@okdave 

As many entries are stored in the database under the parent entity. It's meant as a log of previous actions. I also use GetAll in one other case, for a different entity type, but it's a KeysOnly query. Same behaviour. 

I'll try to limit it to something manageable and get back to you. I'll also set up a simple test case too, to see if there's anything else in my code that's causing this. 

No problem! This is really weirding me out, too...

**Comment by pcostell** [comment]
/cc @eddavisson since I'm out starting next week.

We'll need the project ID and the rough time when you see this to try to get any logs from the servers.

**Comment by andrewladd** [comment]
@okdave I've tried imposing an arbitrary limit, and I still see the same HTTP error. 

The errors I see happen reliably; in every context I use the GetAll function, I see the same failure. I've tried:
- using it inside of a transaction (ie with the `.Transaction(tx)`) function appended to the query
- using different interface set ups 
    - `var entries []*Entry`
    - `entries := make([]*Entry, 0)`
    - `entries := []*Entry{}`
- using a `.KeysOnly()` query versus not.

Also, here's a little more information about how I'm setting up my emulator: 
`/opt/google-cloud-sdk/platform/cloud-datastore-emulator/cloud_datastore_emulator start --host=localhost --port=8832 --store_on_disk=False --consistency=0.9 --allow_remote_shutdown`

**Comment by andrewladd** [comment]
@pcostell I'm not too comfortable posting our project Id publicly. Would it be okay to send it to your (and @eddavisson's) posted email accounts?

**Comment by eddavisson** [comment]
@andrewladd, yep, you can send your project ID to those email accounts.

Are you running these requests against the emulator or against a production datastore?

**Comment by andrewladd** [comment]
@eddavisson I've run them against both: everything runs perfectly against the emulator, but I get this error when against production: 

`rpc error: code = 13 desc = stream terminated by RST_STREAM with error code: 2`

**Comment by eddavisson** [comment]
@andrewladd, thanks for the additional info in the email. I believe you're running into https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/132.

Your query requires an index:

```
- kind: Entry
  ancestor: yes
  properties:
  - name: PatchTime
```

The API attempts to return this recommended index in the error message, but a bug causes the `RST_STREAM` error instead.

**Comment by andrewladd** [comment]
@eddavisson The solution works! Kind of an unexpected turn of events. I'll make sure to use the on-site GQL tester for my queries from now on, and hope to avoid these in the future.

Thanks for the support, everyone! :smiley:
