### ISSUE TITLE
datastore: meaning + GeoPoint

### ISSUE THREAD

**Issue by PSG-Luna** [GoogleCloudPlatform/gcloud-golang#46]
In the v3 proto file used by appengine, a lot of use is made of the "meaning" field to keep track whether something is a geopoint, byte array, time, etc. 
In the v1 public API, the meaning field is specificly marked as "do not use", and additional Value fields have been added, it mostly maps over nicely, however, GeoPoint seems to be gone and I'm somewhat at loss as to how geopoint should be implemented with the new v1 proto API.

**Comment by cnbuff410** [comment]
Is there a ETA for the new API? Looks like 1 year past and no news on it yet?

**Comment by okdave** [comment]
@pcostell do you have an update on timing?

**Comment by pcostell** [comment]
Sorry, I don't have a great answer here. As we were working on the new API
we decided to also redo the infrastructure supporting the API to reduce
latency and improve a number of outstanding issues with the existing API.

My best answer is soon. We are getting closer to launch but want to make
sure the new system works well before releasing it.

**Comment by cnbuff410** [comment]
Now that the v1beta3 is out, is GeoPoint supported now?

**Comment by okdave** [comment]
Not yet, but you're right: it will be possible. Hopefully towards the ends of next week I'll be able to get to it if no one beats me to it.
