### ISSUE TITLE
storage: PutObject API

### ISSUE THREAD

**Issue by bradfitz** [GoogleCloudPlatform/gcloud-golang#86]
Why does PutObject take a bucket and name string, when it's already in the info Object?

```
https://godoc.org/google.golang.org/cloud/storage#PutObject
func PutObject(ctx context.Context, bucket, name string, info *Object) (*Object, error)
PutObject updates an object with the provided meta information.
````

And why does it return an Object? Is that the same Object I passed in?

The docs don't say whether it returns a different pointer, or updates the value in-place via the pointer. It says "updates".

**Comment by rakyll** [comment]
Fixed in https://code-review.googlesource.com/#/c/1630/.
