### ISSUE TITLE
Project objective and state?

### ISSUE THREAD

**Issue by DallanQ** [GoogleCloudPlatform/gcloud-golang#93]
I just came across this project. I've been using the auto-generated google-api-go-client up until now. What is the objective for this project: Is it intended as an alternative to google-api-go-client when you only need access to datastore, cloud storage, pub/sub, and container engine? Is it ready for production use for datastore and cloud storage?

**Comment by rakyll** [comment]
> with the intent of providing a higher-level api abstraction on top of that library. Is that correct?

Correct.

> Also, it appears ready for production use for cloud storage and datastore

It's still a work-in-progress package, we will announce it once it's stable. We're breaking the APIs now and then. If you are not vendoring the package, we may occasionally break you.
