### ISSUE TITLE
Change imports of code.google.com/p/goprotobuf/proto to github.com/golang/protobuf/proto ?

### ISSUE THREAD

**Issue by DallanQ** [GoogleCloudPlatform/gcloud-golang#94]
The page at https://code.google.com/p/goprotobuf/ says that the project has been moved to github: https://github.com/golang/protobuf They modified the package name during the move from goprotobuf to just protobuf.  Looks like it moved about a month ago.

**Comment by rakyll** [comment]
Done. 63f232638e7ed454705e23d5ddbfec493b0b407f
