### ISSUE TITLE
Getting this to work in a managed VM

### ISSUE THREAD

**Issue by DallanQ** [GoogleCloudPlatform/gcloud-golang#96]
In case anyone else is trying to get this to work in a manged VM environment, here's what I did:

Step 1. get the library

`go get google.golang.org/cloud`
// init functions in examples set up their own http handlers, which we don't want
`rm -rf google.golang.org/cloud/examples`
`rm -rf google.golang.org/api/examples`
// KeepAlive was introduced in go 1.3; managed-vm is still on go 1.2.2
comment out KeepAlive in google.golang.org/cloud/compute/metadata/metadata.go 

Step 2. get the dependencies

`go get golang.org/x/oauth2`
comment out KeepAlive in golang.org/x/oauth2/google/google.go
`go get github.com/golang/protobuf/proto`
`go get golang.org/x/text`
`go get google.golang.org/appengine`
`rm -rf google.golang.org/appengine/demos`

Step 3. add "apt-get update" to the generated Dockerfile; otherwise we get an error about failing to fetch  http://security.debian.org/pool/updates/main/l/linux/linux-libc-dev_3.2.63-2+deb7u1_amd64.deb

run `gcloud preview app run` to generate the initial Dockerfile
add `apt-get update && ` to the start of the first RUN statement

Step 4. Authenticate

// for authentication, the example in this file: https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/examples/storage/appenginevm/app.go doesn't work for me when I try to run the app locally. I get the same timeout error as I do when trying to run the appengine guestbook demo locally.  For more information, see http://stackoverflow.com/questions/27715967/cant-get-the-go-guestbook-demo-for-google-app-engine-managed-vm-to-run-locally As far as I can tell, the mock appengine environment that runs when you deploy a managed-vm locally is broken.

// instead, authenticate using a service account as described here:
    https://godoc.org/golang.org/x/oauth2/google#example-JWTConfigFromJSON
    conf, err := google.JWTConfigFromJSON(oauth2.NoContext, jsonKeyBytes,
    	storage.ScopeFullControl, datastore.ScopeDatastore, datastore.ScopeUserEmail)
    if err != nil {
    	log.Fatal(err)
    }
    client := conf.Client(oauth2.NoContext)
    ctx := cloud.NewContext(projectID, client) // according to Luna, the context object is thread-safe and can be shared among requests

Now you can run your app locally or deploy it - it works either way.

__Questions__:

Is there a better way to get gcloud-golang and its dependencies?

Is it safe for me to run on go 1.2.2 by simply commenting out the KeepAlive's in metadata.go and google.go as described above? My example program seems to work, but should I be concerned that underneath something is broken / will break?

Does anyone know how much longer before managed-vm's are on go 1.4?

**Comment by rakyll** [comment]
@okdave, when could we land go1.4 to the Managed VMs?

**Comment by rakyll** [comment]
The package should be working on Managed VMs now. https://code-review.googlesource.com/#/c/1670/

**Comment by DallanQ** [comment]
Thank you!
