### ISSUE TITLE
datastore: Get (and GetMulti) return a nil error instead of ErrNoSuchEntity

### ISSUE THREAD

**Issue by ivanpi-mtv** [GoogleCloudPlatform/gcloud-golang#97]
When a Get call is issued for an entity that doesn't exist, it returns a nil error, even though the documentation states it should return ErrNoSuchEntity.

The underlying problem seems to be in the last for...range in GetMulti. It examines only the Found field in LookupResponse, but the keys with no matching entities are in Missing instead.
It also doesn't use the key-to-index mapping (already set up above) when accessing the multiErr array, but assumes that keys in the response are in the same order.
It should iterate through Missing and copy keys and errors from there, as well as through Deferred and return errors for those keys (according to https://github.com/GoogleCloudPlatform/gcloud-golang/issues/76 which implies that an error should be returned in the current implementation, and a retry added in the future).

**Comment by rakyll** [comment]
Mailed https://code-review.googlesource.com/#/c/1682/.

**Comment by rakyll** [comment]
I'm not reopening #76, we're not sure whether it's worth to address it.
