### ISSUE TITLE
Is "ClientID" the best name for signedUrlOptions?

### ISSUE THREAD

**Issue by cnbuff410** [GoogleCloudPlatform/gcloud-golang#98]
In the code, it says 

"ClientID represents the authorizer of the signed URL generation. It is the Google service account client ID from the Google Developers Console."

However, the ID developer is expected to use is actually "EMAIL ADDRESS" in Google Developers Console, not "CLIENT ID". Isn't it confusing?

**Comment by rakyll** [comment]
Mailed https://code-review.googlesource.com/#/c/1712/.

It's not particularly the service account email address, but email addresses are one of the valid identifiers -- but definitely client IDs are invalid as an input.

The new field name is a little ambiguous, but the documentation says a service account email address will work.
