### ISSUE TITLE
Maybe add another context creator?

### ISSUE THREAD

**Issue by karalabe** [GoogleCloudPlatform/gcloud-golang#99]
Currently the way to create a cloud context is through `cloud.NewContext(id, client)`, but creating the client is quite repetitive and not really obvious from a first sight:

On an App Engine application (through a GAE context):
```go
client := &http.Client{
	Transport: &oauth2.Transport{
		Source: google.AppEngineTokenSource(ctx, storage.ScopeFullControl),
		Base: &urlfetch.Transport{
			Context: ctx,
		},
	},
})
```

On a standalone application (through service accounts):
```go
auth := &oauth2.JWTConfig{
	Email:      ServiceAccountEmail,
	PrivateKey: ServiceAccountPrivateKey,
	Scopes:     []string{storage.ScopeFullControl},
	TokenURL:   google.JWTTokenURL,
}
client := auth.Client(oauth2.NoContext, nil)
```

Wouldn't it be worthwhile to insert this client creation code into the NewContext, and instead use something like `NewContext(projectId, authContext, scopes)`, where authContext would be either the GAE context or some service account context `{email, key}`.

Of course, having the possibility to use a custom client may still be useful so I wouldn't throw it out completely, just maybe have a higher level `NewContext` and rename the current one to `WithClient` (similarly to the existing `WithContext`).

I know I could easily write this small code myself, but thought that it could be useful for others too, so why not include it in the lib? Of course, there may be other use cases and/or complications that I'm not aware of, so consider this an idea only :)

**Comment by okdave** [comment]
The `cloud.WithContext` and `cloud.NewContext` are being deprecated in favour of the more-explicit new `NewClient` pattern.
